import type { Config } from "tailwindcss";

export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ['var(--font-display)', 'sans-serif'],
        body: ['var(--font-body)', 'sans-serif'],
      },
      colors: {
        background: 'var(--background)',
        surface: 'var(--surface)',
        'surface-light': 'var(--surface-light)',
        accent: 'var(--accent)',
        'accent-light': 'var(--accent-light)',
        'on-accent': 'var(--on-accent)',
        success: 'var(--success)',
        'success-light': 'var(--success-light)',
        destructive: 'var(--destructive)',
        'destructive-light': 'var(--destructive-light)',
        warning: 'var(--warning)',
        'warning-light': 'var(--warning-light)',
        info: 'var(--info)',
        'info-light': 'var(--info-light)',
        purple: 'var(--purple)',
        'purple-light': 'var(--purple-light)',
        text: 'var(--text)',
        foreground: 'var(--foreground)',
        muted: 'var(--muted)',
        'muted-dark': 'var(--muted-dark)',
        'muted-foreground': 'var(--muted-foreground)',
        ring: 'var(--ring)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        accent: 'var(--shadow-accent)',
        'accent-hover': 'var(--shadow-accent-hover)',
        card: 'var(--shadow-card)',
      },
      borderColor: {
        DEFAULT: 'var(--border)',
        light: 'var(--border-light)',
        medium: 'var(--border-medium)',
        foreground: 'var(--border-foreground)',
        accent: 'var(--border-accent)',
        'accent-light': 'var(--border-accent-light)',
      },
    },
  },
  plugins: [],
} satisfies Config;
