import type { Dict } from './en'

const de: Dict = {
  meta: {
    siteName: 'Digni Digital',
    home: { title: 'Digni Digital — Lücken schließen. Systeme laufen lassen.', desc: 'Digni Digital ist ein Unternehmen für KI-Systeme mit Sitz in Kinshasa. Wir entwerfen, bauen und betreiben Plattformen, KI-Mitarbeiter und Trainings für Schulen, NGOs, öffentliche Einrichtungen und wachsende Unternehmen in der DR Kongo und in ganz Afrika.' },
    work: { title: 'Projekte — Systeme im Einsatz', desc: 'ShuleOS, die Reporting-Plattform für EPIC DRC, Kabinda Lodge, Digni Results, CADRAN und mehr: die Systeme von Digni Digital, mit ehrlichem Status.' },
    services: { title: 'Leistungen — Betrieb, Wachstum und Talente', desc: 'Agentische Systeme und Plattformen, KI-Mitarbeiter und Future-Ready-Training: drei Wege, wie Digni Digital die Lücken schließt, die Organisationen ausbremsen.' },
    products: { title: 'Produkte — eigene Apps und Plattformen', desc: 'ShuleOS, Digni Results, Boutik, Apporte, Zandocod, MTUSDA, DispatchFlow, SwiftDrop und mehr: Software für die afrikanische Realität.' },
    about: { title: 'Über uns — ein KI-Systemunternehmen aus Kinshasa', desc: 'Digni Digital LLC entwirft und betreibt KI-gestützte Infrastruktur für Organisationen in der DR Kongo und in Afrika. Geschichte, Gründer, Werte, Standorte und Registrierungsdaten.' },
    contact: { title: 'Kontakt — beginnen Sie mit einem 30-Minuten-Gespräch', desc: 'Buchen Sie ein Gespräch, schreiben Sie uns auf WhatsApp (+243 822 378 097) oder an growth@digni-digital-llc.com. Büros in Kinshasa und Nairobi.' },
    blog: { title: 'Einblicke — KI-Systeme, Betrieb und Kompetenzen', desc: 'Artikel von Digni Digital über KI-Mitarbeiter, agentische Systeme, digitale Transformation in der DR Kongo und die Fähigkeiten, die junge Afrikanerinnen und Afrikaner heute brauchen.' },
  },
  nav: {
    home: 'Start', work: 'Projekte', services: 'Leistungen', products: 'Produkte', about: 'Über uns', blog: 'Einblicke', contact: 'Kontakt',
    book: 'Gespräch buchen', menu: 'Menü', close: 'Schließen', language: 'Sprache', skip: 'Zum Inhalt springen', allServices: 'Alle Leistungen',
  },
  status: { live: 'Live', deployed: 'Im Einsatz', progress: 'In Arbeit', demo: 'Live-Demo', beta: 'Beta', delivered: 'Geliefert', merged: 'Jetzt Teil von ShuleOS' },
  sector: { all: 'Alle', education: 'Bildung', ngo: 'NGOs & Geber', public: 'Öffentlicher Sektor', hospitality: 'Gastgewerbe', health: 'Gesundheit', commerce: 'Handel', services: 'Dienstleistungen', community: 'Gemeinschaft', logistics: 'Logistik' },
  common: {
    visit: 'Besuchen', openDemo: 'Live-Demo öffnen', openApp: 'App öffnen', readCase: 'Fallstudie lesen', viewCase: 'Projekt ansehen',
    whatWeBuilt: 'Was wir gebaut haben', context: 'Ausgangslage', client: 'Kunde', sector: 'Branche', location: 'Ort', status: 'Status', year: 'Jahr', link: 'Link', role: 'Unsere Rolle',
    allWork: 'Alle Projekte', backToWork: 'Projekte', related: 'Weitere Projekte', stack: 'Technologie', results: 'Berichtete Ergebnisse', quote: 'Das sagt der Kunde',
    textOnly: 'Zum Schutz der Programmdaten zeigen wir keine Bildschirme.', learnMore: 'Mehr erfahren', seeProducts: 'Alle Produkte', next: 'Weiter', prev: 'Zurück',
    closes: 'Schließt', faq: 'Häufige Fragen', getStarted: 'Loslegen', whatsapp: 'WhatsApp', email: 'E-Mail', phone: 'Telefon', minutesRead: 'Min. Lesezeit',
  },
  home: {
    eyebrow: 'KI-Systemunternehmen · Kinshasa',
    h1a: 'Lücken schließen.', h1b: 'Systeme laufen lassen.',
    sub: 'Wir entwerfen, bauen und betreiben KI-gestützte Plattformen, KI-Mitarbeiter und Trainings für Schulen, NGOs, öffentliche Einrichtungen und wachsende Unternehmen in der DR Kongo und in Afrika.',
    cta1: '30-Minuten-Gespräch buchen', cta2: 'Unsere Projekte',
    facts: ['Für geringe Bandbreite gebaut', 'Bereit für Mobile Money', 'English · Français · Swahili · Lingala'],
    trustTitle: 'Systeme im Einsatz oder im Aufbau für',
    posEyebrow: 'Was wir tun',
    posTitle: 'Den meisten Organisationen fehlt nicht die Vision. Ihnen fehlt die Infrastruktur.',
    posBody: 'Nachrichten bleiben unbeantwortet. Berichte werden jedes Quartal von Hand neu gebaut. Gute Leute verbringen ihren Tag damit, Informationen hin und her zu schieben. Wir ersetzen das durch Systeme, die Ihrem Team gehören und die es versteht, mit KI-Agenten für die wiederkehrende Arbeit dazwischen.',
    pillarsTitle: 'Drei Wege, Lücken zu schließen',
    pillarsSub: 'Beginnen Sie mit der Lücke, die Sie am meisten kostet. Jede Leistung funktioniert für sich und wird mit den anderen stärker.',
    proofEyebrow: 'Belege statt Versprechen',
    proofTitle: 'Projekte im Einsatz',
    proofSub: 'Benannte Projekte mit ehrlichem Status. Was nicht belegt ist, veröffentlichen wir nicht.',
    appsTitle: 'Apps, die wir selbst bauen und betreiben',
    demosEyebrow: 'Selbst ausprobieren',
    demosTitle: 'Zwei öffentliche Demos, die Sie sofort öffnen können',
    demosSub: 'Beispieldaten, ohne Anmeldung. Gebaut, um Gebern, Ministerien und Programmteams zu zeigen, wie die Arbeit laufen könnte.',
    logosEyebrow: 'Kunden und Partner',
    logosTitle: 'Organisationen, mit denen wir gearbeitet haben',
    logosSub: 'Schulen, Stiftungen, Kliniken, Agenturen und wachsende Unternehmen in Kenia, der DR Kongo und darüber hinaus.',
    processTitle: 'So läuft ein Projekt',
    process: [
      ['Analysieren', 'Verstehen, wie die Arbeit wirklich läuft: Menschen, Tools, Konnektivität, Sprachen, Budget.'],
      ['Gestalten', 'Abläufe, Rollen und Erfolgskriterien, gemeinsam mit den späteren Nutzern entworfen.'],
      ['Bauen', 'Kurze Sprints mit Demos. Sicherheit und Datenschutz vom ersten Tag an.'],
      ['Pilotieren', 'Ein klar abgegrenzter Pilot mit echten Nutzern vor jeder langen Bindung.'],
      ['Schulen & übergeben', 'Ihr Team geschult, Dokumentation in Ihrer Sprache, Admin-Zugang auf Ihren Namen.'],
      ['Verbessern', 'Wir beobachten die echte Nutzung und verfeinern laufend.'],
    ],
    sectorsTitle: 'Für wen wir bauen',
    sectors: [
      ['NGOs & Geberprogramme', 'M&E, Reporting und Feldwerkzeuge, die schwache Netze überstehen.'],
      ['Regierung & öffentlicher Sektor', 'Register, Statistiken und Bürgerdienste, demo-bereit für Ausschreibungen.'],
      ['Schulen', 'Schulgebühren, Zeugnisse, Anwesenheit und Elternkommunikation.'],
      ['Gastgewerbe', 'Buchungen, Gästeerlebnis und täglicher Betrieb.'],
      ['KMU & Handel', 'Verkauf, Lager, Mobile Money und Kundenservice rund um die Uhr.'],
    ],
    ctaTitle: 'Sagen Sie uns, wo die Arbeit versickert.',
    ctaSub: 'Ein 30-Minuten-Gespräch. Wir benennen die Lücke und sagen Ihnen ehrlich, ob ein System sie schließen kann.',
    ctaWhatsApp: 'Per WhatsApp schreiben',
  },
  work: {
    eyebrow: 'Projekte', title: 'Systeme, die wir gebaut haben, mit ehrlichem Status.',
    sub: 'Schulen, ein NGO-Programm, eine Lodge, Demos für den öffentlichen Sektor, Kundenprojekte und eigene Produkte.',
    filter: 'Nach Branche filtern', count: 'Projekte',
    ctaTitle: 'Sie haben ein solches System im Kopf?', ctaSub: 'Sagen Sie uns, was immer wieder hakt. Wir zeigen Ihnen, was wir bauen würden und was ein Pilot kostet.',
  },
  services: {
    eyebrow: 'Leistungen', title: 'Betrieb, Wachstum und Talente.',
    sub: 'Drei Leistungen, ein Ziel: weniger Abstand zwischen dem, was Ihre Organisation vorhat, und dem, was jeden Tag tatsächlich passiert.',
    order: 'Der Betrieb steht an erster Stelle, weil dort die meisten unserer Referenzen liegen.',
    pricingTitle: 'So kalkulieren wir',
    pricing: [
      ['Erst ein Pilot', 'Ein abgegrenzter Pilot mit echten Nutzern, damit Sie Ergebnisse vor einer längeren Bindung beurteilen können.'],
      ['Klarer Umfang', 'Projekte mit festem Umfang und Anzahlung. Keine Überraschungsrechnungen.'],
      ['Betreiben & verbessern', 'Monatlicher Support für Systeme, die wir mit Ihnen betreiben: Hosting, Korrekturen, neue Abläufe.'],
    ],
    assessTitle: 'Nicht sicher, wo Sie anfangen sollen?', assessSub: 'Zu jeder Leistung gibt es einen kurzen Eignungscheck. Zehn Fragen, eine ehrliche Antwort und eine umsetzbare Empfehlung.',
    fitCheck: 'Eignungscheck starten',
  },
  products: {
    eyebrow: 'Produkte', title: 'Apps und Plattformen, die uns gehören und die wir betreiben.',
    sub: 'Gebaut für die afrikanische Realität: lückenhafte Netze, Mobile Money und mehrere Sprachen auf einem Bildschirm.',
    groups: { platforms: 'Plattformen für Institutionen', apps: 'Apps für Menschen und Händler', demos: 'Öffentliche Demos', tools: 'KI-Tools' },
    guideTitle: 'DigniGuide fragen', guideSub: 'Unser KI-Guide beantwortet Fragen zu Digni Digital in Ihrer Sprache und führt Sie zum passenden System.',
    requestAccess: 'Zugang anfragen', formerly: 'Früher AMS',
  },
  about: {
    eyebrow: 'Über uns', title: 'Ein Systemunternehmen aus Kinshasa.',
    sub: 'Digni Digital entwirft und betreibt KI-gestützte Infrastruktur für Organisationen in der DR Kongo und in Afrika. Im Besitz des Kunden, verstanden von seinem Team.',
    storyTitle: 'Unsere Geschichte',
    story: [
      ['2018', 'Die Arbeit beginnt als Flashrankmedia, später Digny Consulting, mit Automatisierungs- und Leadgenerierungssystemen für Gründer und KMU.'],
      ['2018–2022', 'Unser Gründer konzipiert und unterrichtet Webentwicklungsprogramme mit NGOs in Kenia und bildet über 30 Entwickler in Gruppen von 15 bis 30 aus.'],
      ['2025', 'Daraus wird die Digni Digital LLC, registriert in Wyoming (USA), im Tagesgeschäft tätig von Kinshasa und Nairobi aus.'],
      ['2026', 'ShuleOS ist an zwei Schulen in der DR Kongo im Einsatz. FHI 360 wählt unseren Gründer aus, um die digitale Reporting-Plattform für EPIC DRC zu bauen.'],
    ],
    founderTitle: 'Gründer',
    founderRole: 'Gründer & COO · Leitender Systementwickler',
    founderBio: 'Pascal baut KI-Systeme, maßgeschneiderte Plattformen und Trainingsprogramme für Organisationen in der DR Kongo und in Kenia. Er hat ShuleOS entwickelt und wurde von FHI 360 als Berater für den Aufbau der Reporting-Plattform von EPIC DRC ausgewählt. Er arbeitet auf Englisch, Französisch, Swahili und Lingala.',
    founderLink: 'Auf LinkedIn vernetzen',
    valuesTitle: 'Wie wir arbeiten',
    values: [
      ['Systeme statt Hype', 'Funktionierende Infrastruktur und klare Ergebnisse statt Schlagworte.'],
      ['Für die Realität gebaut', 'Ungleiche Konnektivität, knappe Budgets, unterschiedliche digitale Kenntnisse, viele Sprachen.'],
      ['Eigentum beim Kunden', 'Ihre Daten, Ihre Automatisierungen und Ihr Admin-Zugang gehören Ihnen.'],
      ['Messen, was zählt', 'Weniger verpasste Chancen und schnellere Antworten. Keine Eitelkeitskennzahlen.'],
    ],
    officesTitle: 'Wo wir sind',
    procTitle: 'Für Einkaufsteams',
    procSub: 'Die Angaben, nach denen Prüfer üblicherweise fragen. Sie brauchen ein Leistungsprofil oder eine Unternehmensübersicht? Schreiben Sie uns, wir senden sie noch am selben Tag.',
    proc: [
      ['Firmenname', 'Digni Digital LLC'],
      ['Rechtsform', 'Limited Liability Company, Bundesstaat Wyoming, USA'],
      ['Gegründet', '1. September 2025 · Entity ID 2025-001757821 · in good standing'],
      ['Eingetragener Sitz', '30 N Gould St Ste R, Sheridan, WY 82801, USA'],
      ['Betrieb', 'Kinshasa, DR Kongo · Nairobi, Kenia'],
      ['Arbeitssprachen', 'Englisch, Französisch, Swahili, Lingala'],
    ],
    procCta: 'Unternehmensprofil anfordern',
  },
  contact: {
    eyebrow: 'Kontakt', title: 'Beginnen Sie mit einem 30-Minuten-Gespräch.',
    sub: 'Sagen Sie uns, was immer wieder hakt. Wir sagen Ihnen ehrlich, ob ein System das lösen kann und wie ein Pilot aussähe.',
    book: 'Gespräch buchen', bookSub: 'Wählen Sie einen Termin in unserem Kalender.',
    wa: 'WhatsApp', waSub: 'Schnellste Antwort zu Geschäftszeiten in Kinshasa.',
    mail: 'E-Mail', mailSub: 'Für Ausschreibungen, Angebote und Dokumente.',
    formTitle: 'Oder schreiben Sie uns', formSub: 'Wir antworten innerhalb eines Werktags.',
    name: 'Ihr Name', org: 'Organisation', email: 'E-Mail', service: 'Was brauchen Sie?', message: 'Was soll das System lösen?',
    serviceOptions: { 'agentic-softwares': 'Agentische Systeme & Plattformen', 'ai-employee': 'KI-Mitarbeiter', 'future-ready-graduate': 'Future-Ready-Training', other: 'Etwas anderes' },
    send: 'Nachricht senden', sending: 'Wird gesendet…', sent: 'Danke. Ihre Nachricht ist unterwegs, wir antworten innerhalb eines Werktags.',
    error: 'Ihre Nachricht konnte nicht gesendet werden. Bitte schreiben Sie an growth@digni-digital-llc.com oder per WhatsApp.',
    privacy: 'Wir nutzen Ihre Angaben nur, um Ihnen zu antworten.',
    officesTitle: 'Büros', directions: 'Route',
    offices: { kinshasa: 'Kinshasa, DR Kongo', nairobi: 'Nairobi, Kenia', sheridan: 'Sheridan, Wyoming, USA' },
    officeRoles: { kinshasa: 'Betrieb · Hauptbüro in Afrika', nairobi: 'Betrieb', sheridan: 'Eingetragener Sitz' },
  },
  blog: {
    eyebrow: 'Einblicke', title: 'Notizen zu KI-Systemen, Betrieb und Kompetenzen.',
    sub: 'Praxisnahe Texte aus unserer Arbeit in Kinshasa und Nairobi: KI-Mitarbeiter, agentische Systeme, digitale Transformation und die Fähigkeiten, die junge Afrikanerinnen und Afrikaner heute brauchen.',
    featured: 'Neu', all: 'Alle Artikel', page: 'Seite', of: 'von', read: 'Artikel lesen', empty: 'Noch keine Artikel.',
  },
  guide: { label: 'DigniGuide fragen', short: 'DigniGuide', title: 'DigniGuide', sub: 'Fragen Sie alles über Digni Digital. Antworten in Ihrer Sprache.', open: 'Vollbild', close: 'Schließen' },
  footer: {
    tagline: 'KI-Systeme für afrikanische Organisationen. Gebaut in Kinshasa.',
    company: 'Unternehmen', servicesCol: 'Leistungen', more: 'Mehr', contactCol: 'Kontakt',
    careers: 'Karriere', affiliate: 'Partnerprogramm', learn: 'Lernplattform', digni: 'DigniGuide',
    privacy: 'Datenschutz', terms: 'AGB', cookies: 'Cookies',
    rights: 'Digni Digital LLC. Alle Rechte vorbehalten.', reg: 'Registriert in Wyoming, USA · Tätig von Kinshasa und Nairobi aus',
    credits: 'Fotos: Unsplash (Unsplash-Lizenz). App-Bildschirme: Projekte von Digni Digital.',
  },
  notFound: { title: 'Diese Seite wurde verschoben oder existiert nicht.', sub: 'Die Website wurde neu aufgebaut. Versuchen Sie eine dieser Seiten.', home: 'Zur Startseite' },
}

export default de
