/**
 * V2 site copy — English (source of truth for the Dict type).
 * Every other locale file must satisfy `Dict`. Keep facts aligned with
 * applying/output/Digni_Digital_Master_Company_Profile.md — never invent numbers.
 */
const en = {
  meta: {
    siteName: 'Digni Digital',
    home: { title: 'Digni Digital — Close the gaps. Let the systems run.', desc: 'Digni Digital is an AI systems company in Kinshasa. We design, build and run platforms, AI employees and training for schools, NGOs, public institutions and growing businesses in the DRC and across Africa.' },
    work: { title: 'Work — systems in production', desc: 'ShuleOS, the EPIC DRC reporting platform, Kabinda Lodge, Digni Results, CADRAN and more: the systems Digni Digital has built, with honest status.' },
    services: { title: 'Services — operations, growth and talent', desc: 'Agentic systems and platforms, AI Employee and Future Ready training: three ways Digni Digital closes the gaps that slow organisations down.' },
    products: { title: 'Products — apps and platforms we own', desc: 'ShuleOS, Digni Results, Boutik, Apporte, Zandocod, MTUSDA, DispatchFlow, SwiftDrop and more: software built for how Africa actually works.' },
    about: { title: 'About — an AI systems company built in Kinshasa', desc: 'Digni Digital LLC designs and runs AI-powered infrastructure for organisations in the DRC and across Africa. Our story, founder, values, offices and registration facts.' },
    contact: { title: 'Contact — start with a 30-minute call', desc: 'Book a call, message us on WhatsApp (+243 822 378 097) or write to growth@digni-digital-llc.com. Offices in Kinshasa and Nairobi.' },
    blog: { title: 'Insights — AI systems, operations and skills', desc: 'Articles from Digni Digital on AI employees, agentic systems, digital transformation in the DRC and the skills young Africans need now.' },
  },
  nav: {
    home: 'Home', work: 'Work', services: 'Services', products: 'Products', about: 'About', blog: 'Insights', contact: 'Contact',
    book: 'Book a call', menu: 'Menu', close: 'Close', language: 'Language', skip: 'Skip to content', allServices: 'All services',
  },
  status: { live: 'Live', deployed: 'Deployed', progress: 'In progress', demo: 'Live demo', beta: 'Beta', delivered: 'Delivered', merged: 'Now part of ShuleOS' },
  sector: { all: 'All', education: 'Education', ngo: 'NGOs & donors', public: 'Public sector', hospitality: 'Hospitality', health: 'Health', commerce: 'Commerce', services: 'Professional services', community: 'Community', logistics: 'Logistics' },
  common: {
    visit: 'Visit', openDemo: 'Open live demo', openApp: 'Open app', readCase: 'Read the case study', viewCase: 'View case',
    whatWeBuilt: 'What we built', context: 'The context', client: 'Client', sector: 'Sector', location: 'Location', status: 'Status', year: 'Year', link: 'Link', role: 'Our role',
    allWork: 'See all work', backToWork: 'All work', related: 'More work', stack: 'Technology', results: 'Reported results', quote: 'What the client said',
    textOnly: 'Screens are not shown to protect programme data.', learnMore: 'Learn more', seeProducts: 'See all products', next: 'Next', prev: 'Previous',
    closes: 'Closes', faq: 'Questions people ask', getStarted: 'Get started', whatsapp: 'WhatsApp', email: 'Email', phone: 'Phone', minutesRead: 'min read',
  },
  home: {
    eyebrow: 'AI systems company · Kinshasa',
    h1a: 'Close the gaps.', h1b: 'Let the systems run.',
    sub: 'We design, build and run AI-powered platforms, AI employees and training for schools, NGOs, public institutions and growing businesses across the DRC and Africa.',
    cta1: 'Book a 30-minute call', cta2: 'See our work',
    facts: ['Built for low bandwidth', 'Mobile money ready', 'English · Français · Swahili · Lingala'],
    trustTitle: 'Systems in use or in build for',
    posEyebrow: 'What we do',
    posTitle: 'Most organisations don’t have a vision problem. They have an infrastructure problem.',
    posBody: 'Messages go unanswered. Reports are rebuilt by hand every quarter. Good people spend their day moving information around. We replace that with systems your team owns and understands, with AI agents doing the repetitive work in between.',
    pillarsTitle: 'Three ways we close the gaps',
    pillarsSub: 'Start with the gap that costs you most. Each service works on its own and gets stronger with the others.',
    proofEyebrow: 'Proof, not promises',
    proofTitle: 'Work in production',
    proofSub: 'Named projects with honest status. Where a number isn’t verified, we don’t print it.',
    appsTitle: 'Apps we build and run ourselves',
    demosEyebrow: 'Try it yourself',
    demosTitle: 'Two public demos you can open right now',
    demosSub: 'Sample data, no sign-up. Built to show donors, ministries and programme teams how the work could run.',
    logosEyebrow: 'Clients and partners',
    logosTitle: 'Organisations we’ve worked with',
    logosSub: 'Schools, foundations, clinics, agencies and growing companies in Kenya, the DRC and beyond.',
    processTitle: 'How an engagement runs',
    process: [
      ['Diagnose', 'Map how the work really happens: people, tools, connectivity, languages, budget.'],
      ['Design', 'Workflows, roles and success measures, designed with the people who will use them.'],
      ['Build', 'Short sprints with demos. Security and privacy from day one.'],
      ['Pilot', 'A scoped pilot with real users before any long commitment.'],
      ['Train & hand over', 'Your team trained, documented in your language, admin access in your name.'],
      ['Improve', 'We watch real usage and keep refining.'],
    ] as [string, string][],
    sectorsTitle: 'Who we build for',
    sectors: [
      ['NGOs & donor programmes', 'M&E, reporting and field tools that survive weak networks.'],
      ['Government & public sector', 'Registers, statistics and citizen services, demo-ready for bids.'],
      ['Schools', 'Fees, report cards, attendance and parent communication.'],
      ['Hospitality', 'Bookings, guest experience and daily operations.'],
      ['SMEs & retail', 'Sales, stock, mobile money and round-the-clock customer response.'],
    ] as [string, string][],
    ctaTitle: 'Tell us where the work leaks.',
    ctaSub: 'A 30-minute call. We map the gap and tell you honestly whether a system will close it.',
    ctaWhatsApp: 'WhatsApp us',
  },
  work: {
    eyebrow: 'Work', title: 'Systems we’ve built, with honest status.',
    sub: 'Schools, an NGO programme, a lodge, public-sector demos, client projects and our own products.',
    filter: 'Filter by sector', count: 'projects',
    ctaTitle: 'Have a system like this in mind?', ctaSub: 'Tell us what keeps slipping. We’ll show you what we would build, and what a pilot would cost.',
  },
  services: {
    eyebrow: 'Services', title: 'Operations, growth and talent.',
    sub: 'Three services, one goal: fewer gaps between what your organisation intends and what actually happens every day.',
    order: 'Operations comes first because that is where most of our proof is.',
    pricingTitle: 'How we price',
    pricing: [
      ['Pilot first', 'A scoped pilot with real users so you can judge results before a longer commitment.'],
      ['Clear scope', 'Fixed-scope builds with a project deposit. No surprise invoices.'],
      ['Run & improve', 'Monthly support for systems we operate with you: hosting, fixes, new workflows.'],
    ] as [string, string][],
    assessTitle: 'Not sure where to start?', assessSub: 'Each service has a short fit check. Ten questions, an honest answer, and a recommendation you can act on.',
    fitCheck: 'Take the fit check',
  },
  products: {
    eyebrow: 'Products', title: 'Apps and platforms we own and run.',
    sub: 'Built for how Africa actually works: patchy networks, mobile money and several languages on one screen.',
    groups: { platforms: 'Platforms for institutions', apps: 'Apps for people and merchants', demos: 'Public demos', tools: 'AI tools' },
    guideTitle: 'Ask DigniGuide', guideSub: 'Our AI guide answers questions about Digni Digital in your language and points you to the right system.',
    requestAccess: 'Request access', formerly: 'Formerly AMS',
  },
  about: {
    eyebrow: 'About', title: 'A systems company built in Kinshasa.',
    sub: 'Digni Digital designs and runs AI-powered infrastructure for organisations in the DRC and across Africa. Owned by the client, understood by their team.',
    storyTitle: 'Our story',
    story: [
      ['2018', 'The practice begins as Flashrankmedia, later Digny Consulting, building automation and lead-generation systems for entrepreneurs and SMEs.'],
      ['2018–2022', 'Our founder designs and teaches web-development programmes with NGOs in Kenya, training 30+ developers in cohorts of 15–30.'],
      ['2025', 'The practice becomes Digni Digital LLC, registered in Wyoming, USA, operating day to day from Kinshasa and Nairobi.'],
      ['2026', 'ShuleOS deployed in two DRC schools. Our founder is selected by FHI 360 to build the EPIC DRC digital reporting platform.'],
    ] as [string, string][],
    founderTitle: 'Founder',
    founderRole: 'Founder & COO · Lead systems developer',
    founderBio: 'Pascal builds AI systems, custom platforms and training programmes for organisations in the DRC and Kenya. He built ShuleOS and was selected by FHI 360 as consultant to build the EPIC DRC reporting platform. He works in English, French, Swahili and Lingala.',
    founderLink: 'Connect on LinkedIn',
    valuesTitle: 'How we work',
    values: [
      ['Systems over hype', 'Working infrastructure and clear outcomes, not buzzwords.'],
      ['Built for reality', 'Uneven connectivity, tight budgets, mixed digital literacy, many languages.'],
      ['Client ownership', 'You own your data, your automations and your admin access.'],
      ['Measure what matters', 'Fewer missed opportunities and faster responses. No vanity metrics.'],
    ] as [string, string][],
    officesTitle: 'Where we are',
    procTitle: 'For procurement teams',
    procSub: 'The facts evaluators usually ask for. Need a capability statement or company profile? Email us and we’ll send it the same day.',
    proc: [
      ['Registered name', 'Digni Digital LLC'],
      ['Entity type', 'Limited Liability Company, State of Wyoming, USA'],
      ['Formed', '1 September 2025 · Entity ID 2025-001757821 · in good standing'],
      ['Registered office', '30 N Gould St Ste R, Sheridan, WY 82801, USA'],
      ['Operations', 'Kinshasa, DRC · Nairobi, Kenya'],
      ['Working languages', 'English, French, Swahili, Lingala'],
    ] as [string, string][],
    procCta: 'Request our company profile',
  },
  contact: {
    eyebrow: 'Contact', title: 'Start with a 30-minute call.',
    sub: 'Tell us what keeps slipping. We’ll tell you honestly whether a system can close it, and what a pilot would look like.',
    book: 'Book a call', bookSub: 'Pick a slot in our calendar.',
    wa: 'WhatsApp', waSub: 'Fastest reply during Kinshasa hours.',
    mail: 'Email', mailSub: 'For RFPs, bids and documents.',
    formTitle: 'Or write to us', formSub: 'We reply within one business day.',
    name: 'Your name', org: 'Organisation', email: 'Email', service: 'What do you need?', message: 'What should the system fix?',
    serviceOptions: { 'agentic-softwares': 'Agentic systems & platforms', 'ai-employee': 'AI Employee', 'future-ready-graduate': 'Future Ready training', other: 'Something else' },
    send: 'Send message', sending: 'Sending…', sent: 'Thank you. Your message is on its way, and we’ll reply within one business day.',
    error: 'We couldn’t send your message. Please email growth@digni-digital-llc.com or message us on WhatsApp.',
    privacy: 'We only use your details to reply to you.',
    officesTitle: 'Offices', directions: 'Directions',
    offices: { kinshasa: 'Kinshasa, DRC', nairobi: 'Nairobi, Kenya', sheridan: 'Sheridan, Wyoming, USA' },
    officeRoles: { kinshasa: 'Operations · main office in Africa', nairobi: 'Operations', sheridan: 'Registered office' },
  },
  blog: {
    eyebrow: 'Insights', title: 'Notes on AI systems, operations and skills.',
    sub: 'Practical writing from our work in Kinshasa and Nairobi: AI employees, agentic systems, digital transformation and the skills young Africans need now.',
    featured: 'Latest', all: 'All articles', page: 'Page', of: 'of', read: 'Read article', empty: 'No articles yet.',
  },
  guide: { label: 'Ask DigniGuide', short: 'DigniGuide', title: 'DigniGuide', sub: 'Ask anything about Digni Digital. Answers in your language.', open: 'Open full screen', close: 'Close' },
  footer: {
    tagline: 'AI systems for African organisations. Built in Kinshasa.',
    company: 'Company', servicesCol: 'Services', more: 'More', contactCol: 'Contact',
    careers: 'Careers', affiliate: 'Affiliate programme', learn: 'Learning platform', digni: 'DigniGuide',
    privacy: 'Privacy', terms: 'Terms', cookies: 'Cookies',
    rights: 'Digni Digital LLC. All rights reserved.', reg: 'Registered in Wyoming, USA · Operating from Kinshasa and Nairobi',
    credits: 'Photography: Unsplash (Unsplash License). App screens: Digni Digital projects.',
  },
  notFound: { title: 'This page moved or never existed.', sub: 'The site was rebuilt recently. Try one of these instead.', home: 'Back to home' },
}

export type Dict = typeof en
export default en
