import type { Dict } from './en'

const es: Dict = {
  meta: {
    siteName: 'Digni Digital',
    home: { title: 'Digni Digital — Cierra las brechas. Deja que los sistemas trabajen.', desc: 'Digni Digital es una empresa de sistemas de IA con sede en Kinsasa. Diseñamos, construimos y operamos plataformas, empleados IA y formación para colegios, ONG, instituciones públicas y empresas en crecimiento en la RD del Congo y en toda África.' },
    work: { title: 'Proyectos — sistemas en producción', desc: 'ShuleOS, la plataforma de reportes de EPIC RDC, Kabinda Lodge, Digni Results, CADRAN y más: los sistemas que ha construido Digni Digital, con su estado real.' },
    services: { title: 'Servicios — operaciones, crecimiento y talento', desc: 'Sistemas agénticos y plataformas, Empleado IA y formación Future Ready: tres formas en que Digni Digital cierra las brechas que frenan a las organizaciones.' },
    products: { title: 'Productos — apps y plataformas propias', desc: 'ShuleOS, Digni Results, Boutik, Apporte, Zandocod, MTUSDA, DispatchFlow, SwiftDrop y más: software hecho para cómo funciona África de verdad.' },
    about: { title: 'Nosotros — una empresa de sistemas de IA nacida en Kinsasa', desc: 'Digni Digital LLC diseña y opera infraestructura con IA para organizaciones en la RD del Congo y en África. Nuestra historia, fundador, valores, oficinas y datos de registro.' },
    contact: { title: 'Contacto — empieza con una llamada de 30 minutos', desc: 'Reserva una llamada, escríbenos por WhatsApp (+243 822 378 097) o a growth@digni-digital-llc.com. Oficinas en Kinsasa y Nairobi.' },
    blog: { title: 'Ideas — sistemas de IA, operaciones y habilidades', desc: 'Artículos de Digni Digital sobre empleados IA, sistemas agénticos, transformación digital en la RD del Congo y las habilidades que necesitan hoy los jóvenes africanos.' },
  },
  nav: {
    home: 'Inicio', work: 'Proyectos', services: 'Servicios', products: 'Productos', about: 'Nosotros', blog: 'Ideas', contact: 'Contacto',
    book: 'Reservar llamada', menu: 'Menú', close: 'Cerrar', language: 'Idioma', skip: 'Ir al contenido', allServices: 'Todos los servicios',
  },
  status: { live: 'En línea', deployed: 'Implantado', progress: 'En curso', demo: 'Demo en vivo', beta: 'Beta', delivered: 'Entregado', merged: 'Ahora parte de ShuleOS' },
  sector: { all: 'Todos', education: 'Educación', ngo: 'ONG y donantes', public: 'Sector público', hospitality: 'Hostelería', health: 'Salud', commerce: 'Comercio', services: 'Servicios profesionales', community: 'Comunidad', logistics: 'Logística' },
  common: {
    visit: 'Visitar', openDemo: 'Abrir la demo', openApp: 'Abrir la app', readCase: 'Leer el caso', viewCase: 'Ver el proyecto',
    whatWeBuilt: 'Qué construimos', context: 'El contexto', client: 'Cliente', sector: 'Sector', location: 'Ubicación', status: 'Estado', year: 'Año', link: 'Enlace', role: 'Nuestro papel',
    allWork: 'Ver todos los proyectos', backToWork: 'Proyectos', related: 'Más proyectos', stack: 'Tecnología', results: 'Resultados reportados', quote: 'Lo que dijo el cliente',
    textOnly: 'No mostramos pantallas para proteger los datos del programa.', learnMore: 'Saber más', seeProducts: 'Ver todos los productos', next: 'Siguiente', prev: 'Anterior',
    closes: 'Cierra', faq: 'Preguntas frecuentes', getStarted: 'Empezar', whatsapp: 'WhatsApp', email: 'Correo', phone: 'Teléfono', minutesRead: 'min de lectura',
  },
  home: {
    eyebrow: 'Empresa de sistemas de IA · Kinsasa',
    h1a: 'Cierra las brechas.', h1b: 'Deja que los sistemas trabajen.',
    sub: 'Diseñamos, construimos y operamos plataformas con IA, empleados IA y formación para colegios, ONG, instituciones públicas y empresas en crecimiento en la RD del Congo y en África.',
    cta1: 'Reservar una llamada de 30 min', cta2: 'Ver nuestros proyectos',
    facts: ['Pensado para poco ancho de banda', 'Listo para dinero móvil', 'English · Français · Swahili · Lingala'],
    trustTitle: 'Sistemas en uso o en construcción para',
    posEyebrow: 'Qué hacemos',
    posTitle: 'La mayoría de las organizaciones no tienen un problema de visión. Tienen un problema de infraestructura.',
    posBody: 'Los mensajes quedan sin respuesta. Los informes se rehacen a mano cada trimestre. Gente valiosa pasa el día moviendo información de un sitio a otro. Lo sustituimos por sistemas que tu equipo posee y entiende, con agentes de IA que hacen el trabajo repetitivo entre medias.',
    pillarsTitle: 'Tres formas de cerrar las brechas',
    pillarsSub: 'Empieza por la brecha que más te cuesta. Cada servicio funciona por sí solo y se refuerza con los demás.',
    proofEyebrow: 'Pruebas, no promesas',
    proofTitle: 'Proyectos en producción',
    proofSub: 'Proyectos con nombre y estado real. Si una cifra no está verificada, no la publicamos.',
    appsTitle: 'Apps que construimos y operamos nosotros mismos',
    demosEyebrow: 'Pruébalo tú mismo',
    demosTitle: 'Dos demos públicas que puedes abrir ahora',
    demosSub: 'Datos de ejemplo, sin registro. Hechas para mostrar a donantes, ministerios y equipos de programa cómo podría funcionar el trabajo.',
    logosEyebrow: 'Clientes y socios',
    logosTitle: 'Organizaciones con las que hemos trabajado',
    logosSub: 'Colegios, fundaciones, clínicas, agencias y empresas en crecimiento en Kenia, la RD del Congo y más allá.',
    processTitle: 'Cómo es un proyecto con nosotros',
    process: [
      ['Diagnosticar', 'Entender cómo ocurre realmente el trabajo: personas, herramientas, conectividad, idiomas, presupuesto.'],
      ['Diseñar', 'Flujos, roles e indicadores de éxito, diseñados con quienes los van a usar.'],
      ['Construir', 'Sprints cortos con demos. Seguridad y privacidad desde el primer día.'],
      ['Pilotar', 'Un piloto acotado con usuarios reales antes de cualquier compromiso largo.'],
      ['Formar y entregar', 'Tu equipo formado, documentación en tu idioma y acceso de administrador a tu nombre.'],
      ['Mejorar', 'Observamos el uso real y seguimos afinando.'],
    ],
    sectorsTitle: 'Para quién construimos',
    sectors: [
      ['ONG y programas de donantes', 'Seguimiento y evaluación, reportes y herramientas de campo que resisten redes débiles.'],
      ['Gobierno y sector público', 'Registros, estadísticas y servicios al ciudadano, listos para demostrar en licitaciones.'],
      ['Colegios', 'Pensiones, boletines, asistencia y comunicación con las familias.'],
      ['Hostelería', 'Reservas, experiencia del huésped y operación diaria.'],
      ['Pymes y comercio', 'Ventas, inventario, dinero móvil y atención al cliente a cualquier hora.'],
    ],
    ctaTitle: 'Cuéntanos por dónde se escapa el trabajo.',
    ctaSub: 'Una llamada de 30 minutos. Identificamos la brecha y te decimos con franqueza si un sistema puede cerrarla.',
    ctaWhatsApp: 'Escríbenos por WhatsApp',
  },
  work: {
    eyebrow: 'Proyectos', title: 'Sistemas que hemos construido, con su estado real.',
    sub: 'Colegios, un programa de ONG, un lodge, demos para el sector público, proyectos de clientes y nuestros propios productos.',
    filter: 'Filtrar por sector', count: 'proyectos',
    ctaTitle: '¿Tienes en mente un sistema así?', ctaSub: 'Cuéntanos qué se te escapa. Te mostraremos qué construiríamos y cuánto costaría un piloto.',
  },
  services: {
    eyebrow: 'Servicios', title: 'Operaciones, crecimiento y talento.',
    sub: 'Tres servicios, un objetivo: menos distancia entre lo que tu organización se propone y lo que realmente ocurre cada día.',
    order: 'Las operaciones van primero porque ahí está la mayor parte de nuestra experiencia demostrada.',
    pricingTitle: 'Cómo fijamos precios',
    pricing: [
      ['Primero un piloto', 'Un piloto acotado con usuarios reales para que juzgues los resultados antes de un compromiso mayor.'],
      ['Alcance claro', 'Proyectos de alcance cerrado con depósito inicial. Sin facturas sorpresa.'],
      ['Operar y mejorar', 'Soporte mensual para los sistemas que operamos contigo: alojamiento, correcciones, nuevos flujos.'],
    ],
    assessTitle: '¿No sabes por dónde empezar?', assessSub: 'Cada servicio tiene un diagnóstico breve. Diez preguntas, una respuesta honesta y una recomendación práctica.',
    fitCheck: 'Hacer el diagnóstico',
  },
  products: {
    eyebrow: 'Productos', title: 'Apps y plataformas que poseemos y operamos.',
    sub: 'Hechas para cómo funciona África de verdad: redes irregulares, dinero móvil y varios idiomas en una misma pantalla.',
    groups: { platforms: 'Plataformas para instituciones', apps: 'Apps para personas y comercios', demos: 'Demos públicas', tools: 'Herramientas de IA' },
    guideTitle: 'Pregunta a DigniGuide', guideSub: 'Nuestra guía con IA responde preguntas sobre Digni Digital en tu idioma y te orienta hacia el sistema adecuado.',
    requestAccess: 'Solicitar acceso', formerly: 'Antes AMS',
  },
  about: {
    eyebrow: 'Nosotros', title: 'Una empresa de sistemas nacida en Kinsasa.',
    sub: 'Digni Digital diseña y opera infraestructura con IA para organizaciones en la RD del Congo y en África. Propiedad del cliente y comprendida por su equipo.',
    storyTitle: 'Nuestra historia',
    story: [
      ['2018', 'La actividad empieza como Flashrankmedia, después Digny Consulting, creando sistemas de automatización y captación de clientes para emprendedores y pymes.'],
      ['2018–2022', 'Nuestro fundador diseña e imparte programas de desarrollo web con ONG en Kenia y forma a más de 30 desarrolladores en grupos de 15 a 30.'],
      ['2025', 'La actividad se convierte en Digni Digital LLC, registrada en Wyoming (EE. UU.) y operada a diario desde Kinsasa y Nairobi.'],
      ['2026', 'ShuleOS se implanta en dos colegios de la RD del Congo. FHI 360 selecciona a nuestro fundador para construir la plataforma digital de reportes de EPIC RDC.'],
    ],
    founderTitle: 'Fundador',
    founderRole: 'Fundador y COO · Desarrollador principal de sistemas',
    founderBio: 'Pascal construye sistemas de IA, plataformas a medida y programas de formación para organizaciones en la RD del Congo y Kenia. Creó ShuleOS y fue seleccionado por FHI 360 como consultor para construir la plataforma de reportes de EPIC RDC. Trabaja en inglés, francés, suajili y lingala.',
    founderLink: 'Conectar en LinkedIn',
    valuesTitle: 'Cómo trabajamos',
    values: [
      ['Sistemas, no humo', 'Infraestructura que funciona y resultados claros, no palabras de moda.'],
      ['Hecho para la realidad', 'Conectividad desigual, presupuestos ajustados, distintos niveles digitales, muchos idiomas.'],
      ['El cliente es dueño', 'Tus datos, tus automatizaciones y tu acceso de administrador son tuyos.'],
      ['Medir lo que importa', 'Menos oportunidades perdidas y respuestas más rápidas. Nada de métricas de vanidad.'],
    ],
    officesTitle: 'Dónde estamos',
    procTitle: 'Para equipos de compras',
    procSub: 'Los datos que suelen pedir los evaluadores. ¿Necesitas una ficha de capacidades o el perfil de la empresa? Escríbenos y te lo enviamos el mismo día.',
    proc: [
      ['Razón social', 'Digni Digital LLC'],
      ['Tipo de entidad', 'Limited Liability Company, estado de Wyoming, EE. UU.'],
      ['Constitución', '1 de septiembre de 2025 · Entity ID 2025-001757821 · en regla'],
      ['Domicilio registrado', '30 N Gould St Ste R, Sheridan, WY 82801, EE. UU.'],
      ['Operaciones', 'Kinsasa, RD del Congo · Nairobi, Kenia'],
      ['Idiomas de trabajo', 'Inglés, francés, suajili, lingala'],
    ],
    procCta: 'Solicitar el perfil de la empresa',
  },
  contact: {
    eyebrow: 'Contacto', title: 'Empieza con una llamada de 30 minutos.',
    sub: 'Cuéntanos qué se te escapa. Te diremos con franqueza si un sistema puede resolverlo y cómo sería un piloto.',
    book: 'Reservar llamada', bookSub: 'Elige un hueco en nuestro calendario.',
    wa: 'WhatsApp', waSub: 'La respuesta más rápida, en horario de Kinsasa.',
    mail: 'Correo', mailSub: 'Para licitaciones, propuestas y documentos.',
    formTitle: 'O escríbenos', formSub: 'Respondemos en un día hábil.',
    name: 'Tu nombre', org: 'Organización', email: 'Correo', service: '¿Qué necesitas?', message: '¿Qué debería resolver el sistema?',
    serviceOptions: { 'agentic-softwares': 'Sistemas agénticos y plataformas', 'ai-employee': 'Empleado IA', 'future-ready-graduate': 'Formación Future Ready', other: 'Otra cosa' },
    send: 'Enviar mensaje', sending: 'Enviando…', sent: 'Gracias. Tu mensaje está en camino y te responderemos en un día hábil.',
    error: 'No pudimos enviar tu mensaje. Escribe a growth@digni-digital-llc.com o contáctanos por WhatsApp.',
    privacy: 'Solo usamos tus datos para responderte.',
    officesTitle: 'Oficinas', directions: 'Cómo llegar',
    offices: { kinshasa: 'Kinsasa, RD del Congo', nairobi: 'Nairobi, Kenia', sheridan: 'Sheridan, Wyoming, EE. UU.' },
    officeRoles: { kinshasa: 'Operaciones · oficina principal en África', nairobi: 'Operaciones', sheridan: 'Domicilio registrado' },
  },
  blog: {
    eyebrow: 'Ideas', title: 'Notas sobre sistemas de IA, operaciones y habilidades.',
    sub: 'Textos prácticos desde nuestro trabajo en Kinsasa y Nairobi: empleados IA, sistemas agénticos, transformación digital y las habilidades que necesitan hoy los jóvenes africanos.',
    featured: 'Lo último', all: 'Todos los artículos', page: 'Página', of: 'de', read: 'Leer artículo', empty: 'Aún no hay artículos.',
  },
  guide: { label: 'Pregunta a DigniGuide', short: 'DigniGuide', title: 'DigniGuide', sub: 'Pregunta lo que quieras sobre Digni Digital. Respuestas en tu idioma.', open: 'Pantalla completa', close: 'Cerrar' },
  footer: {
    tagline: 'Sistemas de IA para organizaciones africanas. Hechos en Kinsasa.',
    company: 'Empresa', servicesCol: 'Servicios', more: 'Más', contactCol: 'Contacto',
    careers: 'Empleo', affiliate: 'Programa de afiliados', learn: 'Plataforma de formación', digni: 'DigniGuide',
    privacy: 'Privacidad', terms: 'Condiciones', cookies: 'Cookies',
    rights: 'Digni Digital LLC. Todos los derechos reservados.', reg: 'Registrada en Wyoming, EE. UU. · Operamos desde Kinsasa y Nairobi',
    credits: 'Fotografía: Unsplash (licencia Unsplash). Pantallas: proyectos de Digni Digital.',
  },
  notFound: { title: 'Esta página se movió o nunca existió.', sub: 'Hemos renovado el sitio. Prueba con una de estas páginas.', home: 'Volver al inicio' },
}

export default es
