import type { Dict } from './en'

const fr: Dict = {
  meta: {
    siteName: 'Digni Digital',
    home: { title: 'Digni Digital — Fermez les failles. Laissez les systèmes tourner.', desc: 'Digni Digital est une entreprise de systèmes IA basée à Kinshasa. Nous concevons, construisons et exploitons des plateformes, des employés IA et des formations pour écoles, ONG, institutions publiques et entreprises en croissance en RDC et en Afrique.' },
    work: { title: 'Réalisations — des systèmes en production', desc: 'ShuleOS, la plateforme de reporting EPIC RDC, Kabinda Lodge, Digni Results, CADRAN et plus : les systèmes construits par Digni Digital, avec leur statut réel.' },
    services: { title: 'Services — opérations, croissance et talents', desc: 'Systèmes agentiques et plateformes, Employé IA et formation Future Ready : trois façons dont Digni Digital ferme les failles qui freinent les organisations.' },
    products: { title: 'Produits — applications et plateformes maison', desc: 'ShuleOS, Digni Results, Boutik, Apporte, Zandocod, MTUSDA, DispatchFlow, SwiftDrop et plus : des logiciels pensés pour l’Afrique telle qu’elle fonctionne.' },
    about: { title: 'À propos — une entreprise de systèmes IA née à Kinshasa', desc: 'Digni Digital LLC conçoit et exploite des infrastructures propulsées par l’IA pour les organisations en RDC et en Afrique. Notre histoire, notre fondateur, nos valeurs, nos bureaux et nos informations légales.' },
    contact: { title: 'Contact — commencez par un appel de 30 minutes', desc: 'Réservez un appel, écrivez-nous sur WhatsApp (+243 822 378 097) ou à growth@digni-digital-llc.com. Bureaux à Kinshasa et Nairobi.' },
    blog: { title: 'Analyses — systèmes IA, opérations et compétences', desc: 'Articles de Digni Digital sur les employés IA, les systèmes agentiques, la transformation numérique en RDC et les compétences dont les jeunes Africains ont besoin aujourd’hui.' },
  },
  nav: {
    home: 'Accueil', work: 'Réalisations', services: 'Services', products: 'Produits', about: 'À propos', blog: 'Analyses', contact: 'Contact',
    book: 'Réserver un appel', menu: 'Menu', close: 'Fermer', language: 'Langue', skip: 'Aller au contenu', allServices: 'Tous les services',
  },
  status: { live: 'En ligne', deployed: 'Déployé', progress: 'En cours', demo: 'Démo en ligne', beta: 'Bêta', delivered: 'Livré', merged: 'Intégré à ShuleOS' },
  sector: { all: 'Tous', education: 'Éducation', ngo: 'ONG & bailleurs', public: 'Secteur public', hospitality: 'Hôtellerie', health: 'Santé', commerce: 'Commerce', services: 'Services professionnels', community: 'Communauté', logistics: 'Logistique' },
  common: {
    visit: 'Visiter', openDemo: 'Ouvrir la démo', openApp: 'Ouvrir l’application', readCase: 'Lire l’étude de cas', viewCase: 'Voir le projet',
    whatWeBuilt: 'Ce que nous avons construit', context: 'Le contexte', client: 'Client', sector: 'Secteur', location: 'Lieu', status: 'Statut', year: 'Année', link: 'Lien', role: 'Notre rôle',
    allWork: 'Toutes les réalisations', backToWork: 'Réalisations', related: 'Autres projets', stack: 'Technologies', results: 'Résultats rapportés', quote: 'Ce qu’en dit le client',
    textOnly: 'Les écrans ne sont pas montrés afin de protéger les données du programme.', learnMore: 'En savoir plus', seeProducts: 'Tous les produits', next: 'Suivant', prev: 'Précédent',
    closes: 'Ferme', faq: 'Questions fréquentes', getStarted: 'Commencer', whatsapp: 'WhatsApp', email: 'E-mail', phone: 'Téléphone', minutesRead: 'min de lecture',
  },
  home: {
    eyebrow: 'Entreprise de systèmes IA · Kinshasa',
    h1a: 'Fermez les failles.', h1b: 'Laissez les systèmes tourner.',
    sub: 'Nous concevons, construisons et exploitons des plateformes propulsées par l’IA, des employés IA et des formations pour écoles, ONG, institutions publiques et entreprises en croissance en RDC et en Afrique.',
    cta1: 'Réserver un appel de 30 min', cta2: 'Voir nos réalisations',
    facts: ['Pensé pour les faibles débits', 'Compatible mobile money', 'English · Français · Swahili · Lingala'],
    trustTitle: 'Systèmes en service ou en construction pour',
    posEyebrow: 'Ce que nous faisons',
    posTitle: 'La plupart des organisations n’ont pas un problème de vision. Elles ont un problème d’infrastructure.',
    posBody: 'Les messages restent sans réponse. Les rapports sont refaits à la main chaque trimestre. Des gens compétents passent leur journée à déplacer de l’information. Nous remplaçons cela par des systèmes que votre équipe possède et comprend, avec des agents IA qui font le travail répétitif entre les deux.',
    pillarsTitle: 'Trois façons de fermer les failles',
    pillarsSub: 'Commencez par la faille qui vous coûte le plus. Chaque service fonctionne seul et se renforce avec les autres.',
    proofEyebrow: 'Des preuves, pas des promesses',
    proofTitle: 'Des réalisations en production',
    proofSub: 'Des projets nommés, avec leur statut réel. Quand un chiffre n’est pas vérifié, nous ne le publions pas.',
    appsTitle: 'Des applications que nous construisons et exploitons nous-mêmes',
    demosEyebrow: 'Essayez vous-même',
    demosTitle: 'Deux démos publiques à ouvrir dès maintenant',
    demosSub: 'Données fictives, sans inscription. Conçues pour montrer aux bailleurs, ministères et équipes de programme comment le travail pourrait fonctionner.',
    logosEyebrow: 'Clients et partenaires',
    logosTitle: 'Ils nous ont fait confiance',
    logosSub: 'Écoles, fondations, cliniques, agences et entreprises en croissance au Kenya, en RDC et au-delà.',
    processTitle: 'Le déroulement d’une mission',
    process: [
      ['Diagnostiquer', 'Comprendre comment le travail se fait vraiment : personnes, outils, connectivité, langues, budget.'],
      ['Concevoir', 'Processus, rôles et indicateurs de réussite, conçus avec ceux qui les utiliseront.'],
      ['Construire', 'Des sprints courts avec démos. Sécurité et confidentialité dès le premier jour.'],
      ['Piloter', 'Un pilote cadré avec de vrais utilisateurs avant tout engagement long.'],
      ['Former et transmettre', 'Votre équipe formée, une documentation dans votre langue, les accès admin à votre nom.'],
      ['Améliorer', 'Nous suivons l’usage réel et continuons d’affiner.'],
    ],
    sectorsTitle: 'Pour qui nous construisons',
    sectors: [
      ['ONG et programmes financés', 'Suivi-évaluation, reporting et outils de terrain qui résistent aux réseaux faibles.'],
      ['Gouvernement et secteur public', 'Registres, statistiques et services aux citoyens, prêts à être démontrés lors d’appels d’offres.'],
      ['Écoles', 'Frais scolaires, bulletins, présences et communication avec les parents.'],
      ['Hôtellerie', 'Réservations, expérience client et opérations quotidiennes.'],
      ['PME et commerce', 'Ventes, stocks, mobile money et réponse client à toute heure.'],
    ],
    ctaTitle: 'Dites-nous où le travail fuit.',
    ctaSub: 'Un appel de 30 minutes. Nous identifions la faille et vous disons franchement si un système peut la fermer.',
    ctaWhatsApp: 'Écrire sur WhatsApp',
  },
  work: {
    eyebrow: 'Réalisations', title: 'Les systèmes que nous avons construits, avec leur statut réel.',
    sub: 'Des écoles, un programme d’ONG, un lodge, des démos pour le secteur public, des projets clients et nos propres produits.',
    filter: 'Filtrer par secteur', count: 'projets',
    ctaTitle: 'Vous avez un système de ce type en tête ?', ctaSub: 'Dites-nous ce qui vous échappe. Nous vous montrerons ce que nous construirions et ce que coûterait un pilote.',
  },
  services: {
    eyebrow: 'Services', title: 'Opérations, croissance et talents.',
    sub: 'Trois services, un objectif : réduire l’écart entre ce que votre organisation veut faire et ce qui se passe réellement chaque jour.',
    order: 'Les opérations passent en premier, car c’est là que se trouvent la plupart de nos preuves.',
    pricingTitle: 'Notre façon de tarifer',
    pricing: [
      ['D’abord un pilote', 'Un pilote cadré avec de vrais utilisateurs pour juger des résultats avant un engagement plus long.'],
      ['Un périmètre clair', 'Des projets au périmètre fixé, avec un acompte. Pas de factures surprises.'],
      ['Exploiter et améliorer', 'Un support mensuel pour les systèmes que nous exploitons avec vous : hébergement, corrections, nouveaux processus.'],
    ],
    assessTitle: 'Vous ne savez pas par où commencer ?', assessSub: 'Chaque service a son court diagnostic. Dix questions, une réponse honnête et une recommandation concrète.',
    fitCheck: 'Faire le diagnostic',
  },
  products: {
    eyebrow: 'Produits', title: 'Des applications et plateformes que nous possédons et exploitons.',
    sub: 'Pensées pour l’Afrique telle qu’elle fonctionne : réseaux irréguliers, mobile money et plusieurs langues sur un même écran.',
    groups: { platforms: 'Plateformes pour les institutions', apps: 'Applications pour particuliers et commerçants', demos: 'Démos publiques', tools: 'Outils IA' },
    guideTitle: 'Demandez à DigniGuide', guideSub: 'Notre guide IA répond à vos questions sur Digni Digital dans votre langue et vous oriente vers le bon système.',
    requestAccess: 'Demander un accès', formerly: 'Anciennement AMS',
  },
  about: {
    eyebrow: 'À propos', title: 'Une entreprise de systèmes née à Kinshasa.',
    sub: 'Digni Digital conçoit et exploite des infrastructures propulsées par l’IA pour les organisations en RDC et en Afrique. Elles appartiennent au client et son équipe les comprend.',
    storyTitle: 'Notre histoire',
    story: [
      ['2018', 'L’activité démarre sous le nom de Flashrankmedia, puis Digny Consulting, avec des systèmes d’automatisation et de génération de prospects pour entrepreneurs et PME.'],
      ['2018–2022', 'Notre fondateur conçoit et enseigne des programmes de développement web avec des ONG au Kenya et forme plus de 30 développeurs par cohortes de 15 à 30.'],
      ['2025', 'L’activité devient Digni Digital LLC, enregistrée dans le Wyoming (États-Unis) et opérée au quotidien depuis Kinshasa et Nairobi.'],
      ['2026', 'ShuleOS est déployé dans deux écoles en RDC. FHI 360 sélectionne notre fondateur pour construire la plateforme de reporting numérique d’EPIC RDC.'],
    ],
    founderTitle: 'Fondateur',
    founderRole: 'Fondateur & COO · Développeur principal des systèmes',
    founderBio: 'Pascal construit des systèmes IA, des plateformes sur mesure et des programmes de formation pour des organisations en RDC et au Kenya. Il a créé ShuleOS et a été sélectionné par FHI 360 comme consultant pour construire la plateforme de reporting d’EPIC RDC. Il travaille en anglais, français, swahili et lingala.',
    founderLink: 'Le suivre sur LinkedIn',
    valuesTitle: 'Notre façon de travailler',
    values: [
      ['Des systèmes, pas du battage', 'Une infrastructure qui fonctionne et des résultats clairs, pas des mots à la mode.'],
      ['Pensé pour le terrain', 'Connectivité inégale, budgets serrés, niveaux numériques variés, plusieurs langues.'],
      ['Le client propriétaire', 'Vos données, vos automatisations et vos accès admin vous appartiennent.'],
      ['Mesurer l’essentiel', 'Moins d’occasions manquées et des réponses plus rapides. Pas d’indicateurs de façade.'],
    ],
    officesTitle: 'Où nous trouver',
    procTitle: 'Pour les équipes achats',
    procSub: 'Les informations que demandent généralement les évaluateurs. Besoin d’une fiche de capacités ou d’une présentation de l’entreprise ? Écrivez-nous, nous l’envoyons le jour même.',
    proc: [
      ['Raison sociale', 'Digni Digital LLC'],
      ['Forme juridique', 'Limited Liability Company, État du Wyoming, États-Unis'],
      ['Création', '1er septembre 2025 · Entity ID 2025-001757821 · en règle'],
      ['Siège social', '30 N Gould St Ste R, Sheridan, WY 82801, États-Unis'],
      ['Opérations', 'Kinshasa, RDC · Nairobi, Kenya'],
      ['Langues de travail', 'Anglais, français, swahili, lingala'],
    ],
    procCta: 'Demander notre présentation',
  },
  contact: {
    eyebrow: 'Contact', title: 'Commencez par un appel de 30 minutes.',
    sub: 'Dites-nous ce qui vous échappe. Nous vous dirons franchement si un système peut y remédier et à quoi ressemblerait un pilote.',
    book: 'Réserver un appel', bookSub: 'Choisissez un créneau dans notre agenda.',
    wa: 'WhatsApp', waSub: 'La réponse la plus rapide, aux heures de Kinshasa.',
    mail: 'E-mail', mailSub: 'Pour les appels d’offres, soumissions et documents.',
    formTitle: 'Ou écrivez-nous', formSub: 'Nous répondons sous un jour ouvré.',
    name: 'Votre nom', org: 'Organisation', email: 'E-mail', service: 'De quoi avez-vous besoin ?', message: 'Que doit corriger le système ?',
    serviceOptions: { 'agentic-softwares': 'Systèmes agentiques & plateformes', 'ai-employee': 'Employé IA', 'future-ready-graduate': 'Formation Future Ready', other: 'Autre chose' },
    send: 'Envoyer', sending: 'Envoi…', sent: 'Merci. Votre message est bien parti ; nous répondons sous un jour ouvré.',
    error: 'Votre message n’a pas pu être envoyé. Écrivez à growth@digni-digital-llc.com ou contactez-nous sur WhatsApp.',
    privacy: 'Vos informations servent uniquement à vous répondre.',
    officesTitle: 'Bureaux', directions: 'Itinéraire',
    offices: { kinshasa: 'Kinshasa, RDC', nairobi: 'Nairobi, Kenya', sheridan: 'Sheridan, Wyoming, États-Unis' },
    officeRoles: { kinshasa: 'Opérations · bureau principal en Afrique', nairobi: 'Opérations', sheridan: 'Siège social' },
  },
  blog: {
    eyebrow: 'Analyses', title: 'Notes sur les systèmes IA, les opérations et les compétences.',
    sub: 'Des écrits pratiques tirés de notre travail à Kinshasa et Nairobi : employés IA, systèmes agentiques, transformation numérique et compétences dont les jeunes Africains ont besoin aujourd’hui.',
    featured: 'À la une', all: 'Tous les articles', page: 'Page', of: 'sur', read: 'Lire l’article', empty: 'Aucun article pour le moment.',
  },
  guide: { label: 'Demander à DigniGuide', short: 'DigniGuide', title: 'DigniGuide', sub: 'Posez toutes vos questions sur Digni Digital. Réponses dans votre langue.', open: 'Plein écran', close: 'Fermer' },
  footer: {
    tagline: 'Des systèmes IA pour les organisations africaines. Construits à Kinshasa.',
    company: 'Entreprise', servicesCol: 'Services', more: 'Plus', contactCol: 'Contact',
    careers: 'Carrières', affiliate: 'Programme d’affiliation', learn: 'Plateforme de formation', digni: 'DigniGuide',
    privacy: 'Confidentialité', terms: 'Conditions', cookies: 'Cookies',
    rights: 'Digni Digital LLC. Tous droits réservés.', reg: 'Enregistrée dans le Wyoming (États-Unis) · Opérations depuis Kinshasa et Nairobi',
    credits: 'Photographies : Unsplash (licence Unsplash). Écrans : projets Digni Digital.',
  },
  notFound: { title: 'Cette page a été déplacée ou n’a jamais existé.', sub: 'Le site a été entièrement refait. Essayez plutôt l’une de ces pages.', home: 'Retour à l’accueil' },
}

export default fr
