/** Services registry — /services, /services/[slug], home pillars, services.json. */
import type { Lang } from './locales'
import type { CheckoutPlanKey } from '@/lib/stripe/checkout-plans'
import type { AssessmentServiceId } from '@/lib/assessments/types'

export type ServiceSlug = 'agentic-systems' | 'ai-employee' | 'future-ready'

export interface ServiceCopy {
  k: string; name: string; gap: string; body: string; points: string[]
  heroSub: string
  problemTitle: string; problemBody: string
  buildTitle: string; build: [string, string][]
  stepsTitle: string; steps: [string, string][]
  proofTitle: string
  pricingTitle: string; pricingBody: string; checkout: string; checkoutNote: string
  faqs: [string, string][]
  ctaTitle: string; ctaSub: string
}

export interface Service {
  slug: ServiceSlug
  assessment: AssessmentServiceId
  checkoutPlan?: CheckoutPlanKey
  img: string
  heroImg: string
  related: string[]
  copy: Record<Lang, ServiceCopy>
}

const agentic: Record<Lang, ServiceCopy> = {
  en: {
    k: 'Operations', name: 'Agentic Systems & Platforms',
    gap: 'Closes: manual reporting, scattered records, work that waits on one person.',
    body: 'Custom platforms for schools, hotels, programmes and businesses, with AI agents that move work along: reminders, validations, escalations, documents.',
    points: ['School, hotel and M&E platforms', 'Offline-first and role-based', 'Dashboards for management and donors'],
    heroSub: 'We build the platform your organisation actually runs on, then add agents that handle the repetitive steps in between. You own the code, the data and the admin access.',
    problemTitle: 'When the system is a notebook, a spreadsheet and one busy person',
    problemBody: 'Records live in five places. Reports are rebuilt by hand. When the person who knows how it works is away, the work stops. We map that reality first, then design a system around it, not the other way round.',
    buildTitle: 'What we build',
    build: [
      ['Operating platforms', 'School, hotel, programme and operations systems shaped around your roles and workflows.'],
      ['AI agents in the workflow', 'Agents that chase missing data, draft documents, validate entries and escalate what needs a human.'],
      ['Dashboards and reports', 'Live views for management and donors, with exports in the formats you already submit.'],
      ['Offline-first apps', 'Web apps that keep working when the network drops and sync when it returns.'],
      ['Integrations', 'Mobile money, SMS, WhatsApp, email and the tools you already pay for.'],
      ['Hosting and support', 'Secure hosting, backups, monitoring and improvements after go-live.'],
    ],
    stepsTitle: 'From first call to running system',
    steps: [
      ['Discovery', 'One to two weeks mapping people, data, connectivity and the decisions the system must support.'],
      ['First version', 'A working MVP in as little as 7 days for focused tools; larger platforms take 1 to 3 months.'],
      ['Pilot', 'Real users, real data, a short list of success measures agreed up front.'],
      ['Roll-out', 'Training in your language, documentation, and admin access in your name.'],
    ],
    proofTitle: 'Platforms we’ve built',
    pricingTitle: 'Scope first, then a fixed quote',
    pricingBody: 'Every platform is scoped after a discovery call. Small tools start at a few weeks of work; full platforms are quoted per phase. A project deposit secures your build slot.',
    checkout: 'Pay project deposit', checkoutNote: 'Secure payment by Stripe. The deposit is credited to your project.',
    faqs: [
      ['What is an agentic system?', 'Software built around your workflows in which AI agents carry out defined steps, such as following up, checking data or drafting documents, through tools you approve. People stay in charge of decisions.'],
      ['How long does a project take?', 'Focused tools can be live in 7 days to 2 weeks. Larger platforms take 1 to 3 months, delivered in phases with demos along the way.'],
      ['Who owns the software and data?', 'You do. Admin access, data and automations are set up in your organisation’s name.'],
      ['Does it work with poor connectivity?', 'Yes. We design offline-first where it matters and test on the networks your team actually uses.'],
    ],
    ctaTitle: 'Show us the workflow that keeps breaking.', ctaSub: 'In 30 minutes we’ll tell you what we would build first and what it would take.',
  },
  fr: {
    k: 'Opérations', name: 'Systèmes agentiques & plateformes',
    gap: 'Ferme : reporting manuel, dossiers éparpillés, travail bloqué sur une seule personne.',
    body: 'Des plateformes sur mesure pour écoles, hôtels, programmes et entreprises, avec des agents IA qui font avancer le travail : rappels, validations, escalades, documents.',
    points: ['Plateformes école, hôtel et suivi-évaluation', 'Hors ligne d’abord, par rôles', 'Tableaux de bord pour la direction et les bailleurs'],
    heroSub: 'Nous construisons la plateforme sur laquelle votre organisation tourne vraiment, puis nous ajoutons des agents qui gèrent les étapes répétitives. Le code, les données et les accès admin vous appartiennent.',
    problemTitle: 'Quand le système, c’est un cahier, un tableur et une personne débordée',
    problemBody: 'Les dossiers sont à cinq endroits. Les rapports sont refaits à la main. Quand la personne qui sait comment tout fonctionne est absente, le travail s’arrête. Nous partons de cette réalité, puis nous concevons le système autour d’elle, et non l’inverse.',
    buildTitle: 'Ce que nous construisons',
    build: [
      ['Plateformes de gestion', 'Systèmes pour écoles, hôtels, programmes et opérations, adaptés à vos rôles et circuits.'],
      ['Agents IA dans le circuit', 'Des agents qui relancent les données manquantes, rédigent des documents, valident les saisies et remontent ce qui exige un humain.'],
      ['Tableaux de bord et rapports', 'Des vues en direct pour la direction et les bailleurs, avec des exports aux formats que vous soumettez déjà.'],
      ['Applications hors ligne', 'Des applications web qui continuent sans réseau et synchronisent à son retour.'],
      ['Intégrations', 'Mobile money, SMS, WhatsApp, e-mail et les outils que vous payez déjà.'],
      ['Hébergement et support', 'Hébergement sécurisé, sauvegardes, supervision et améliorations après la mise en service.'],
    ],
    stepsTitle: 'Du premier appel au système en service',
    steps: [
      ['Cadrage', 'Une à deux semaines pour cartographier personnes, données, connectivité et décisions à soutenir.'],
      ['Première version', 'Un MVP opérationnel en 7 jours pour un outil ciblé ; 1 à 3 mois pour une plateforme complète.'],
      ['Pilote', 'De vrais utilisateurs, de vraies données et quelques indicateurs de réussite fixés au départ.'],
      ['Déploiement', 'Formation dans votre langue, documentation et accès admin à votre nom.'],
    ],
    proofTitle: 'Plateformes réalisées',
    pricingTitle: 'D’abord le périmètre, ensuite un devis ferme',
    pricingBody: 'Chaque plateforme est cadrée après un appel de découverte. Un petit outil représente quelques semaines de travail ; une plateforme complète est chiffrée par phase. Un acompte réserve votre créneau de développement.',
    checkout: 'Payer l’acompte', checkoutNote: 'Paiement sécurisé par Stripe. L’acompte est déduit du projet.',
    faqs: [
      ['Qu’est-ce qu’un système agentique ?', 'Un logiciel construit autour de vos processus, dans lequel des agents IA exécutent des étapes définies (relancer, vérifier des données, rédiger) via des outils que vous approuvez. Les décisions restent humaines.'],
      ['Combien de temps dure un projet ?', 'Un outil ciblé peut être en ligne en 7 jours à 2 semaines. Une plateforme plus large prend 1 à 3 mois, livrée par phases avec des démos.'],
      ['À qui appartiennent le logiciel et les données ?', 'À vous. Les accès admin, les données et les automatisations sont créés au nom de votre organisation.'],
      ['Ça marche avec une connexion faible ?', 'Oui. Nous concevons hors ligne d’abord quand c’est nécessaire et testons sur les réseaux réellement utilisés par votre équipe.'],
    ],
    ctaTitle: 'Montrez-nous le processus qui casse toujours.', ctaSub: 'En 30 minutes, nous vous disons ce que nous construirions en premier et ce que cela demanderait.',
  },
  es: {
    k: 'Operaciones', name: 'Sistemas agénticos y plataformas',
    gap: 'Cierra: reportes manuales, registros dispersos, trabajo que depende de una sola persona.',
    body: 'Plataformas a medida para colegios, hoteles, programas y empresas, con agentes de IA que hacen avanzar el trabajo: recordatorios, validaciones, escalados, documentos.',
    points: ['Plataformas para colegios, hoteles y M&E', 'Funcionan sin conexión y por roles', 'Paneles para dirección y donantes'],
    heroSub: 'Construimos la plataforma con la que de verdad funciona tu organización y añadimos agentes que se encargan de los pasos repetitivos. El código, los datos y el acceso de administrador son tuyos.',
    problemTitle: 'Cuando el sistema es un cuaderno, una hoja de cálculo y una persona saturada',
    problemBody: 'Los registros están en cinco sitios. Los informes se rehacen a mano. Cuando falta quien sabe cómo funciona todo, el trabajo se para. Partimos de esa realidad y diseñamos el sistema a su alrededor, no al revés.',
    buildTitle: 'Qué construimos',
    build: [
      ['Plataformas de gestión', 'Sistemas para colegios, hoteles, programas y operaciones, adaptados a tus roles y flujos.'],
      ['Agentes de IA en el flujo', 'Agentes que persiguen datos faltantes, redactan documentos, validan entradas y escalan lo que necesita a una persona.'],
      ['Paneles e informes', 'Vistas en vivo para dirección y donantes, con exportaciones en los formatos que ya entregas.'],
      ['Apps sin conexión', 'Apps web que siguen funcionando cuando cae la red y sincronizan al volver.'],
      ['Integraciones', 'Dinero móvil, SMS, WhatsApp, correo y las herramientas que ya pagas.'],
      ['Alojamiento y soporte', 'Alojamiento seguro, copias de seguridad, monitoreo y mejoras tras la puesta en marcha.'],
    ],
    stepsTitle: 'De la primera llamada al sistema en marcha',
    steps: [
      ['Descubrimiento', 'Una o dos semanas para mapear personas, datos, conectividad y las decisiones que debe apoyar el sistema.'],
      ['Primera versión', 'Un MVP funcional en tan solo 7 días para herramientas concretas; las plataformas grandes llevan de 1 a 3 meses.'],
      ['Piloto', 'Usuarios reales, datos reales y unos pocos indicadores de éxito acordados de antemano.'],
      ['Despliegue', 'Formación en tu idioma, documentación y acceso de administrador a tu nombre.'],
    ],
    proofTitle: 'Plataformas que hemos construido',
    pricingTitle: 'Primero el alcance, después un presupuesto cerrado',
    pricingBody: 'Cada plataforma se define tras una llamada de descubrimiento. Una herramienta pequeña son unas semanas de trabajo; una plataforma completa se presupuesta por fases. Un depósito reserva tu turno de desarrollo.',
    checkout: 'Pagar el depósito', checkoutNote: 'Pago seguro con Stripe. El depósito se descuenta del proyecto.',
    faqs: [
      ['¿Qué es un sistema agéntico?', 'Software construido en torno a tus flujos en el que agentes de IA ejecutan pasos definidos, como hacer seguimiento, revisar datos o redactar documentos, con herramientas que tú apruebas. Las decisiones siguen siendo de las personas.'],
      ['¿Cuánto dura un proyecto?', 'Una herramienta concreta puede estar lista en 7 días a 2 semanas. Las plataformas grandes llevan de 1 a 3 meses, entregadas por fases con demos.'],
      ['¿De quién son el software y los datos?', 'Tuyos. El acceso de administrador, los datos y las automatizaciones se crean a nombre de tu organización.'],
      ['¿Funciona con mala conectividad?', 'Sí. Diseñamos para trabajar sin conexión cuando hace falta y probamos en las redes que usa tu equipo.'],
    ],
    ctaTitle: 'Enséñanos el proceso que siempre falla.', ctaSub: 'En 30 minutos te diremos qué construiríamos primero y qué haría falta.',
  },
  de: {
    k: 'Betrieb', name: 'Agentische Systeme & Plattformen',
    gap: 'Schließt: manuelle Berichte, verstreute Daten, Arbeit, die an einer Person hängt.',
    body: 'Maßgeschneiderte Plattformen für Schulen, Hotels, Programme und Unternehmen, mit KI-Agenten, die die Arbeit voranbringen: Erinnerungen, Prüfungen, Eskalationen, Dokumente.',
    points: ['Plattformen für Schulen, Hotels und M&E', 'Offline-fähig und rollenbasiert', 'Dashboards für Leitung und Geber'],
    heroSub: 'Wir bauen die Plattform, auf der Ihre Organisation tatsächlich arbeitet, und ergänzen Agenten für die wiederkehrenden Schritte dazwischen. Code, Daten und Admin-Zugang gehören Ihnen.',
    problemTitle: 'Wenn das System aus einem Notizbuch, einer Tabelle und einer überlasteten Person besteht',
    problemBody: 'Daten liegen an fünf Orten. Berichte werden von Hand neu gebaut. Fehlt die Person, die alles weiß, steht die Arbeit still. Wir erfassen zuerst diese Realität und bauen das System um sie herum, nicht umgekehrt.',
    buildTitle: 'Was wir bauen',
    build: [
      ['Betriebsplattformen', 'Systeme für Schulen, Hotels, Programme und Betrieb, zugeschnitten auf Ihre Rollen und Abläufe.'],
      ['KI-Agenten im Ablauf', 'Agenten, die fehlende Daten nachfassen, Dokumente entwerfen, Eingaben prüfen und an Menschen eskalieren, wenn nötig.'],
      ['Dashboards und Berichte', 'Live-Ansichten für Leitung und Geber, mit Exporten in den Formaten, die Sie bereits einreichen.'],
      ['Offline-fähige Apps', 'Web-Apps, die ohne Netz weiterlaufen und synchronisieren, sobald es zurück ist.'],
      ['Integrationen', 'Mobile Money, SMS, WhatsApp, E-Mail und die Tools, die Sie schon bezahlen.'],
      ['Hosting und Support', 'Sicheres Hosting, Backups, Monitoring und Weiterentwicklung nach dem Start.'],
    ],
    stepsTitle: 'Vom ersten Gespräch zum laufenden System',
    steps: [
      ['Analyse', 'Ein bis zwei Wochen, um Menschen, Daten, Konnektivität und die zu unterstützenden Entscheidungen zu erfassen.'],
      ['Erste Version', 'Ein funktionierendes MVP in nur 7 Tagen für fokussierte Tools; größere Plattformen brauchen 1 bis 3 Monate.'],
      ['Pilot', 'Echte Nutzer, echte Daten und wenige, vorab vereinbarte Erfolgskriterien.'],
      ['Einführung', 'Schulung in Ihrer Sprache, Dokumentation und Admin-Zugang auf Ihren Namen.'],
    ],
    proofTitle: 'Plattformen, die wir gebaut haben',
    pricingTitle: 'Erst der Umfang, dann ein Festpreis',
    pricingBody: 'Jede Plattform wird nach einem Erstgespräch definiert. Kleine Tools sind wenige Wochen Arbeit; vollständige Plattformen werden pro Phase angeboten. Eine Anzahlung sichert Ihren Entwicklungsslot.',
    checkout: 'Anzahlung leisten', checkoutNote: 'Sichere Zahlung über Stripe. Die Anzahlung wird auf das Projekt angerechnet.',
    faqs: [
      ['Was ist ein agentisches System?', 'Software, die um Ihre Abläufe herum gebaut ist und in der KI-Agenten festgelegte Schritte ausführen – nachfassen, Daten prüfen, Dokumente entwerfen – über Tools, die Sie freigeben. Entscheidungen bleiben beim Menschen.'],
      ['Wie lange dauert ein Projekt?', 'Fokussierte Tools können in 7 Tagen bis 2 Wochen live sein. Größere Plattformen dauern 1 bis 3 Monate und werden in Phasen mit Demos geliefert.'],
      ['Wem gehören Software und Daten?', 'Ihnen. Admin-Zugang, Daten und Automatisierungen werden auf den Namen Ihrer Organisation eingerichtet.'],
      ['Funktioniert das bei schlechter Verbindung?', 'Ja. Wo nötig, bauen wir offline-fähig und testen in den Netzen, die Ihr Team wirklich nutzt.'],
    ],
    ctaTitle: 'Zeigen Sie uns den Ablauf, der ständig hakt.', ctaSub: 'In 30 Minuten sagen wir Ihnen, was wir zuerst bauen würden und was es braucht.',
  },
  ar: {
    k: 'العمليات', name: 'الأنظمة الوكيلية والمنصات',
    gap: 'تغلق: التقارير اليدوية، والسجلات المبعثرة، والعمل المعلّق على شخص واحد.',
    body: 'منصات مخصصة للمدارس والفنادق والبرامج والشركات، مع وكلاء ذكاء اصطناعي يدفعون العمل إلى الأمام: تذكيرات واعتمادات وتصعيد ووثائق.',
    points: ['منصات للمدارس والفنادق والمتابعة والتقييم', 'تعمل دون اتصال أولاً وبصلاحيات', 'لوحات معلومات للإدارة والمانحين'],
    heroSub: 'نبني المنصة التي تعمل عليها مؤسستك فعلاً، ثم نضيف وكلاء يتولون الخطوات المتكررة بينها. الشيفرة والبيانات وصلاحيات الإدارة ملكك.',
    problemTitle: 'حين يكون النظام دفتراً وجدولاً وشخصاً مثقلاً بالعمل',
    problemBody: 'السجلات في خمسة أماكن، والتقارير تُعاد يدوياً، وحين يغيب من يعرف كيف يسير كل شيء يتوقف العمل. نبدأ برسم هذا الواقع ثم نصمم النظام حوله، لا العكس.',
    buildTitle: 'ما نبنيه',
    build: [
      ['منصات تشغيل', 'أنظمة للمدارس والفنادق والبرامج والعمليات مصممة وفق أدواركم ومسارات عملكم.'],
      ['وكلاء ذكاء اصطناعي داخل المسار', 'وكلاء يلاحقون البيانات الناقصة ويصوغون الوثائق ويتحققون من الإدخالات ويصعّدون ما يحتاج إلى إنسان.'],
      ['لوحات وتقارير', 'عروض مباشرة للإدارة والمانحين مع تصدير بالصيغ التي تقدمونها أصلاً.'],
      ['تطبيقات تعمل دون اتصال', 'تطبيقات ويب تواصل العمل عند انقطاع الشبكة وتزامن عند عودتها.'],
      ['تكاملات', 'الدفع عبر الهاتف والرسائل وواتساب والبريد والأدوات التي تدفعون مقابلها.'],
      ['الاستضافة والدعم', 'استضافة آمنة ونسخ احتياطي ومراقبة وتحسينات بعد الإطلاق.'],
    ],
    stepsTitle: 'من المكالمة الأولى إلى نظام يعمل',
    steps: [
      ['الاستكشاف', 'أسبوع إلى أسبوعين لرسم الأشخاص والبيانات والاتصال والقرارات التي يجب أن يدعمها النظام.'],
      ['النسخة الأولى', 'نسخة أولية عاملة في 7 أيام فقط للأدوات المحددة؛ والمنصات الأكبر تستغرق من شهر إلى 3 أشهر.'],
      ['التجربة', 'مستخدمون حقيقيون وبيانات حقيقية وعدد قليل من مؤشرات النجاح المتفق عليها مسبقاً.'],
      ['الإطلاق', 'تدريب بلغتك وتوثيق وصلاحيات إدارة باسمك.'],
    ],
    proofTitle: 'منصات بنيناها',
    pricingTitle: 'النطاق أولاً ثم عرض سعر ثابت',
    pricingBody: 'تُحدد كل منصة بعد مكالمة استكشافية. الأدوات الصغيرة تتطلب أسابيع قليلة من العمل، والمنصات الكاملة تُسعّر لكل مرحلة. دفعة مقدمة تحجز موعد التطوير.',
    checkout: 'ادفع الدفعة المقدمة', checkoutNote: 'دفع آمن عبر Stripe. تُحتسب الدفعة من قيمة المشروع.',
    faqs: [
      ['ما هو النظام الوكيلي؟', 'برنامج مبني حول مسارات عملك، ينفذ فيه وكلاء الذكاء الاصطناعي خطوات محددة مثل المتابعة والتحقق من البيانات وصياغة الوثائق عبر أدوات توافق عليها. وتبقى القرارات بيد البشر.'],
      ['كم يستغرق المشروع؟', 'يمكن إطلاق الأدوات المحددة خلال 7 أيام إلى أسبوعين. أما المنصات الأكبر فتستغرق من شهر إلى 3 أشهر وتُسلّم على مراحل مع عروض توضيحية.'],
      ['لمن تعود ملكية البرنامج والبيانات؟', 'لك. تُنشأ صلاحيات الإدارة والبيانات والأتمتة باسم مؤسستك.'],
      ['هل يعمل مع اتصال ضعيف؟', 'نعم. نصمم للعمل دون اتصال حيث يلزم ونختبر على الشبكات التي يستخدمها فريقك فعلاً.'],
    ],
    ctaTitle: 'أرِنا المسار الذي يتعطل دائماً.', ctaSub: 'خلال 30 دقيقة نخبرك بما سنبنيه أولاً وما يتطلبه ذلك.',
  },
}

const aiEmployee: Record<Lang, ServiceCopy> = {
  en: {
    k: 'Growth', name: 'AI Employee',
    gap: 'Closes: missed calls, unanswered WhatsApps, leads that go cold overnight.',
    body: 'A digital team member that answers on WhatsApp, web chat, SMS and email, qualifies the request and books it into your calendar, around the clock.',
    points: ['Answers in seconds, day and night', 'Qualifies before your staff step in', 'Books, confirms and reminds'],
    heroSub: 'Your AI Employee answers every enquiry in seconds, asks the questions your best staff would ask, and puts qualified conversations straight into your calendar. Your team only steps in when it matters.',
    problemTitle: 'Most leads aren’t lost to competitors. They’re lost to silence.',
    problemBody: 'A message arrives at 9 pm. Nobody answers until the next afternoon. By then the client has called someone else. The AI Employee closes that gap without adding headcount.',
    buildTitle: 'What your AI Employee does',
    build: [
      ['Answers instantly', 'On WhatsApp, web chat, SMS, email and social inboxes, in the languages your clients use.'],
      ['Qualifies', 'Asks your questions, captures the details and filters out what isn’t a fit.'],
      ['Books', 'Offers real slots from your calendar and confirms the appointment.'],
      ['Follows up', 'Sends reminders and gentle follow-ups so fewer people go quiet.'],
      ['Hands over', 'Passes hot conversations to your team with the full history, in your CRM or inbox.'],
      ['Reports', 'Shows what came in, what was booked and where conversations stalled.'],
    ],
    stepsTitle: 'Live in days, not months',
    steps: [
      ['Fit check', 'A short assessment to see where enquiries go cold and whether an AI Employee is the right fix.'],
      ['Set-up', 'We load your services, prices, FAQs and booking rules, and connect your channels.'],
      ['Test', 'You test real conversations before anything goes live.'],
      ['Go live and improve', 'We watch real conversations and tune answers every week.'],
    ],
    proofTitle: 'Related work',
    pricingTitle: 'See the numbers for your business first',
    pricingBody: 'The fit check shows what slow follow-up is costing you and the full investment before you pay anything. Ready already? You can go straight to secure checkout.',
    checkout: 'Continue to secure checkout', checkoutNote: 'Secure payment by Stripe. Amounts are confirmed in your assessment results.',
    faqs: [
      ['Is this just a chatbot?', 'No. It works across your channels, follows your qualification rules, books into your real calendar and follows up. It is set up and tuned for your business.'],
      ['Which channels does it cover?', 'WhatsApp, web chat, SMS, email and social inboxes, depending on what your clients use.'],
      ['What happens with difficult questions?', 'It hands the conversation to your team with the full history, so nobody has to ask twice.'],
      ['Which languages does it speak?', 'English, French and the other languages your clients write in. We test each language before go-live.'],
    ],
    ctaTitle: 'Stop losing the enquiries that arrive after hours.', ctaSub: 'Take the fit check or book a 30-minute call.',
  },
  fr: {
    k: 'Croissance', name: 'Employé IA',
    gap: 'Ferme : appels manqués, WhatsApp sans réponse, prospects perdus pendant la nuit.',
    body: 'Un membre d’équipe numérique qui répond sur WhatsApp, chat web, SMS et e-mail, qualifie la demande et l’inscrit dans votre agenda, jour et nuit.',
    points: ['Répond en quelques secondes, jour et nuit', 'Qualifie avant l’intervention de l’équipe', 'Réserve, confirme et rappelle'],
    heroSub: 'Votre Employé IA répond à chaque demande en quelques secondes, pose les questions que poserait votre meilleur collaborateur et inscrit les échanges qualifiés directement dans votre agenda. Votre équipe n’intervient que lorsque c’est utile.',
    problemTitle: 'La plupart des prospects ne partent pas chez un concurrent. Ils partent faute de réponse.',
    problemBody: 'Un message arrive à 21 h. Personne ne répond avant le lendemain après-midi. Entre-temps, le client a appelé quelqu’un d’autre. L’Employé IA ferme cette faille sans recruter.',
    buildTitle: 'Ce que fait votre Employé IA',
    build: [
      ['Répond tout de suite', 'Sur WhatsApp, chat web, SMS, e-mail et messageries sociales, dans les langues de vos clients.'],
      ['Qualifie', 'Pose vos questions, recueille les informations et écarte ce qui ne correspond pas.'],
      ['Réserve', 'Propose de vrais créneaux de votre agenda et confirme le rendez-vous.'],
      ['Relance', 'Envoie rappels et relances pour que moins de personnes décrochent.'],
      ['Transmet', 'Passe les échanges chauds à votre équipe avec tout l’historique, dans votre CRM ou votre messagerie.'],
      ['Rend compte', 'Montre ce qui est arrivé, ce qui a été réservé et où les échanges se sont arrêtés.'],
    ],
    stepsTitle: 'En ligne en quelques jours, pas en quelques mois',
    steps: [
      ['Diagnostic', 'Une courte évaluation pour voir où les demandes se perdent et si un Employé IA est la bonne réponse.'],
      ['Mise en place', 'Nous chargeons vos services, tarifs, FAQ et règles de réservation, et connectons vos canaux.'],
      ['Test', 'Vous testez de vraies conversations avant toute mise en ligne.'],
      ['Lancement et amélioration', 'Nous suivons les vraies conversations et ajustons les réponses chaque semaine.'],
    ],
    proofTitle: 'Réalisations liées',
    pricingTitle: 'Voyez d’abord les chiffres pour votre activité',
    pricingBody: 'Le diagnostic montre ce que vous coûtent les relances trop lentes et l’investissement total, avant tout paiement. Déjà décidé ? Passez directement au paiement sécurisé.',
    checkout: 'Continuer vers le paiement sécurisé', checkoutNote: 'Paiement sécurisé par Stripe. Les montants sont confirmés dans vos résultats.',
    faqs: [
      ['Est-ce un simple chatbot ?', 'Non. Il travaille sur vos canaux, suit vos règles de qualification, réserve dans votre vrai agenda et relance. Il est configuré et ajusté pour votre activité.'],
      ['Quels canaux couvre-t-il ?', 'WhatsApp, chat web, SMS, e-mail et messageries sociales, selon ce qu’utilisent vos clients.'],
      ['Et les questions difficiles ?', 'Il transmet la conversation à votre équipe avec tout l’historique, pour que personne n’ait à répéter.'],
      ['Quelles langues parle-t-il ?', 'Français, anglais et les autres langues de vos clients. Chaque langue est testée avant la mise en ligne.'],
    ],
    ctaTitle: 'Ne perdez plus les demandes qui arrivent après la fermeture.', ctaSub: 'Faites le diagnostic ou réservez un appel de 30 minutes.',
  },
  es: {
    k: 'Crecimiento', name: 'Empleado IA',
    gap: 'Cierra: llamadas perdidas, WhatsApps sin respuesta, clientes que se enfrían por la noche.',
    body: 'Un miembro digital del equipo que responde por WhatsApp, chat web, SMS y correo, califica la solicitud y la agenda en tu calendario, a cualquier hora.',
    points: ['Responde en segundos, día y noche', 'Califica antes de que intervenga tu equipo', 'Agenda, confirma y recuerda'],
    heroSub: 'Tu Empleado IA responde cada consulta en segundos, hace las preguntas que haría tu mejor persona y lleva las conversaciones calificadas directo a tu calendario. Tu equipo solo interviene cuando hace falta.',
    problemTitle: 'La mayoría de los clientes no se pierden por la competencia. Se pierden por el silencio.',
    problemBody: 'Llega un mensaje a las 21 h. Nadie responde hasta la tarde siguiente. Para entonces el cliente ya llamó a otro. El Empleado IA cierra esa brecha sin aumentar plantilla.',
    buildTitle: 'Qué hace tu Empleado IA',
    build: [
      ['Responde al instante', 'Por WhatsApp, chat web, SMS, correo y bandejas sociales, en los idiomas de tus clientes.'],
      ['Califica', 'Hace tus preguntas, recoge los datos y descarta lo que no encaja.'],
      ['Agenda', 'Ofrece huecos reales de tu calendario y confirma la cita.'],
      ['Hace seguimiento', 'Envía recordatorios y seguimientos para que menos gente se quede callada.'],
      ['Deriva', 'Pasa las conversaciones calientes a tu equipo con todo el historial, en tu CRM o bandeja.'],
      ['Informa', 'Muestra lo que entró, lo que se agendó y dónde se estancaron las conversaciones.'],
    ],
    stepsTitle: 'En marcha en días, no en meses',
    steps: [
      ['Diagnóstico', 'Una evaluación breve para ver dónde se enfrían las consultas y si un Empleado IA es la solución.'],
      ['Configuración', 'Cargamos tus servicios, precios, preguntas frecuentes y reglas de reserva, y conectamos tus canales.'],
      ['Prueba', 'Pruebas conversaciones reales antes de publicar nada.'],
      ['Lanzamiento y mejora', 'Observamos las conversaciones reales y ajustamos las respuestas cada semana.'],
    ],
    proofTitle: 'Trabajos relacionados',
    pricingTitle: 'Primero mira los números de tu negocio',
    pricingBody: 'El diagnóstico muestra lo que te cuesta responder tarde y la inversión total antes de pagar nada. ¿Ya lo tienes claro? Ve directo al pago seguro.',
    checkout: 'Continuar al pago seguro', checkoutNote: 'Pago seguro con Stripe. Los importes se confirman en tus resultados.',
    faqs: [
      ['¿Es solo un chatbot?', 'No. Trabaja en tus canales, sigue tus reglas de calificación, agenda en tu calendario real y hace seguimiento. Se configura y ajusta para tu negocio.'],
      ['¿Qué canales cubre?', 'WhatsApp, chat web, SMS, correo y bandejas sociales, según lo que usen tus clientes.'],
      ['¿Qué pasa con las preguntas difíciles?', 'Pasa la conversación a tu equipo con todo el historial, para que nadie tenga que repetir.'],
      ['¿Qué idiomas habla?', 'Inglés, francés y los demás idiomas en que escriben tus clientes. Probamos cada idioma antes del lanzamiento.'],
    ],
    ctaTitle: 'Deja de perder las consultas que llegan fuera de horario.', ctaSub: 'Haz el diagnóstico o reserva una llamada de 30 minutos.',
  },
  de: {
    k: 'Wachstum', name: 'KI-Mitarbeiter',
    gap: 'Schließt: verpasste Anrufe, unbeantwortete WhatsApps, Anfragen, die über Nacht kalt werden.',
    body: 'Ein digitales Teammitglied, das auf WhatsApp, Webchat, SMS und E-Mail antwortet, Anfragen qualifiziert und rund um die Uhr Termine in Ihren Kalender bucht.',
    points: ['Antwortet in Sekunden, Tag und Nacht', 'Qualifiziert, bevor Ihr Team übernimmt', 'Bucht, bestätigt und erinnert'],
    heroSub: 'Ihr KI-Mitarbeiter beantwortet jede Anfrage in Sekunden, stellt die Fragen, die Ihre besten Leute stellen würden, und legt qualifizierte Gespräche direkt in Ihren Kalender. Ihr Team greift nur ein, wenn es zählt.',
    problemTitle: 'Die meisten Anfragen gehen nicht an die Konkurrenz verloren, sondern an die Stille.',
    problemBody: 'Um 21 Uhr kommt eine Nachricht. Bis zum nächsten Nachmittag antwortet niemand. Bis dahin hat der Kunde längst jemand anderen angerufen. Der KI-Mitarbeiter schließt diese Lücke, ohne neues Personal.',
    buildTitle: 'Was Ihr KI-Mitarbeiter tut',
    build: [
      ['Antwortet sofort', 'Auf WhatsApp, Webchat, SMS, E-Mail und Social-Media-Postfächern, in den Sprachen Ihrer Kunden.'],
      ['Qualifiziert', 'Stellt Ihre Fragen, erfasst die Details und filtert aus, was nicht passt.'],
      ['Bucht', 'Bietet echte Termine aus Ihrem Kalender an und bestätigt sie.'],
      ['Fasst nach', 'Sendet Erinnerungen und freundliche Nachfragen, damit weniger Kontakte verstummen.'],
      ['Übergibt', 'Leitet heiße Gespräche mit dem gesamten Verlauf an Ihr Team weiter, im CRM oder Postfach.'],
      ['Berichtet', 'Zeigt, was hereinkam, was gebucht wurde und wo Gespräche stockten.'],
    ],
    stepsTitle: 'In Tagen live, nicht in Monaten',
    steps: [
      ['Eignungscheck', 'Eine kurze Analyse, wo Anfragen kalt werden und ob ein KI-Mitarbeiter die richtige Lösung ist.'],
      ['Einrichtung', 'Wir hinterlegen Leistungen, Preise, FAQs und Buchungsregeln und verbinden Ihre Kanäle.'],
      ['Test', 'Sie testen echte Gespräche, bevor etwas live geht.'],
      ['Start und Optimierung', 'Wir beobachten echte Gespräche und verfeinern die Antworten jede Woche.'],
    ],
    proofTitle: 'Verwandte Projekte',
    pricingTitle: 'Erst die Zahlen für Ihr Geschäft sehen',
    pricingBody: 'Der Eignungscheck zeigt, was langsame Reaktionen Sie kosten, und die gesamte Investition, bevor Sie etwas bezahlen. Schon entschieden? Dann direkt zur sicheren Zahlung.',
    checkout: 'Weiter zur sicheren Zahlung', checkoutNote: 'Sichere Zahlung über Stripe. Beträge werden in Ihren Ergebnissen bestätigt.',
    faqs: [
      ['Ist das nur ein Chatbot?', 'Nein. Er arbeitet über Ihre Kanäle, folgt Ihren Qualifizierungsregeln, bucht in Ihren echten Kalender und fasst nach. Er wird für Ihr Geschäft eingerichtet und abgestimmt.'],
      ['Welche Kanäle deckt er ab?', 'WhatsApp, Webchat, SMS, E-Mail und Social-Media-Postfächer, je nachdem, was Ihre Kunden nutzen.'],
      ['Was passiert bei schwierigen Fragen?', 'Er übergibt das Gespräch mit dem gesamten Verlauf an Ihr Team, damit niemand doppelt fragen muss.'],
      ['Welche Sprachen spricht er?', 'Englisch, Französisch und die weiteren Sprachen Ihrer Kunden. Jede Sprache wird vor dem Start getestet.'],
    ],
    ctaTitle: 'Verlieren Sie keine Anfragen mehr nach Feierabend.', ctaSub: 'Machen Sie den Eignungscheck oder buchen Sie ein 30-Minuten-Gespräch.',
  },
  ar: {
    k: 'النمو', name: 'الموظف الذكي',
    gap: 'تغلق: المكالمات الفائتة، ورسائل واتساب بلا رد، والعملاء الذين يبردون ليلاً.',
    body: 'عضو رقمي في فريقك يرد عبر واتساب والدردشة والرسائل النصية والبريد، ويؤهل الطلب ويحجزه في تقويمك على مدار الساعة.',
    points: ['يرد خلال ثوانٍ ليلاً ونهاراً', 'يؤهل الطلب قبل تدخل فريقك', 'يحجز ويؤكد ويذكّر'],
    heroSub: 'يرد موظفك الذكي على كل استفسار خلال ثوانٍ، ويطرح الأسئلة التي يطرحها أفضل موظفيك، ويضع المحادثات المؤهلة مباشرة في تقويمك. ولا يتدخل فريقك إلا حين يلزم.',
    problemTitle: 'معظم العملاء لا يذهبون إلى المنافسين، بل يضيعون في الصمت.',
    problemBody: 'تصل رسالة في التاسعة مساءً ولا يرد أحد حتى عصر اليوم التالي، وحينها يكون العميل قد اتصل بغيرك. يغلق الموظف الذكي هذه الثغرة دون توظيف إضافي.',
    buildTitle: 'ما يفعله موظفك الذكي',
    build: [
      ['يرد فوراً', 'عبر واتساب والدردشة والرسائل والبريد وصناديق التواصل الاجتماعي، وبلغات عملائك.'],
      ['يؤهل', 'يطرح أسئلتك ويجمع التفاصيل ويستبعد ما لا يناسب.'],
      ['يحجز', 'يعرض مواعيد حقيقية من تقويمك ويؤكد الموعد.'],
      ['يتابع', 'يرسل تذكيرات ومتابعات لطيفة حتى لا ينقطع التواصل.'],
      ['يسلّم', 'ينقل المحادثات المهمة إلى فريقك مع سجلها الكامل في نظامك أو بريدك.'],
      ['يقدم تقارير', 'يُظهر ما وصل وما حُجز وأين توقفت المحادثات.'],
    ],
    stepsTitle: 'جاهز خلال أيام لا أشهر',
    steps: [
      ['فحص الملاءمة', 'تقييم قصير لمعرفة أين تبرد الاستفسارات وهل الموظف الذكي هو الحل المناسب.'],
      ['الإعداد', 'نُدخل خدماتك وأسعارك وأسئلتك الشائعة وقواعد الحجز ونربط قنواتك.'],
      ['الاختبار', 'تختبر محادثات حقيقية قبل أي إطلاق.'],
      ['الإطلاق والتحسين', 'نراقب المحادثات الحقيقية ونحسّن الردود كل أسبوع.'],
    ],
    proofTitle: 'أعمال ذات صلة',
    pricingTitle: 'اطّلع أولاً على أرقام نشاطك',
    pricingBody: 'يُظهر فحص الملاءمة كلفة الرد البطيء والاستثمار الكامل قبل أن تدفع شيئاً. هل قررت بالفعل؟ انتقل مباشرة إلى الدفع الآمن.',
    checkout: 'المتابعة إلى الدفع الآمن', checkoutNote: 'دفع آمن عبر Stripe. تُؤكد المبالغ في نتائج تقييمك.',
    faqs: [
      ['هل هو مجرد روبوت محادثة؟', 'لا. يعمل عبر قنواتك ويتبع قواعد التأهيل لديك ويحجز في تقويمك الحقيقي ويتابع. ويُعدّ ويُضبط خصيصاً لنشاطك.'],
      ['ما القنوات التي يغطيها؟', 'واتساب والدردشة والرسائل النصية والبريد وصناديق التواصل الاجتماعي حسب ما يستخدمه عملاؤك.'],
      ['ماذا عن الأسئلة الصعبة؟', 'ينقل المحادثة إلى فريقك مع سجلها الكامل حتى لا يضطر أحد إلى التكرار.'],
      ['ما اللغات التي يتحدثها؟', 'الإنجليزية والفرنسية واللغات الأخرى التي يكتب بها عملاؤك. نختبر كل لغة قبل الإطلاق.'],
    ],
    ctaTitle: 'توقّف عن خسارة الاستفسارات التي تصل بعد الدوام.', ctaSub: 'أجرِ فحص الملاءمة أو احجز مكالمة من 30 دقيقة.',
  },
}

const futureReady: Record<Lang, ServiceCopy> = {
  en: {
    k: 'Talent', name: 'Future Ready',
    gap: 'Closes: certificates without evidence, teams afraid of AI tools.',
    body: 'Practical AI capability for teams and graduates. Everyone leaves with portfolio evidence: an app, an AI workflow, an automation and a capstone.',
    points: ['Hands-on, not slides', 'Portfolio over certificates', 'For schools, institutes and companies'],
    heroSub: 'A professional readiness programme, not a computer course. Learners build real things with AI tools and leave with a portfolio that proves what they can do.',
    problemTitle: 'Graduates finish with certificates. Employers ask for evidence.',
    problemBody: 'Young people are told to “learn digital skills” but rarely ship anything real. Future Ready is built around projects, so every participant can show an employer, a client or a funder what they built.',
    buildTitle: 'What participants build',
    build: [
      ['An app', 'A working web app, designed and deployed by the learner.'],
      ['An AI workflow', 'A real task done faster and better with AI tools, documented step by step.'],
      ['An automation', 'A repetitive process turned into something that runs on its own.'],
      ['A capstone', 'A project for a real organisation or idea, presented to a panel.'],
      ['A portfolio', 'One page that brings the evidence together for employers and clients.'],
      ['Career skills', 'Communication, freelancing basics and how to create work, not only find it.'],
    ],
    stepsTitle: 'How the programme runs',
    steps: [
      ['Partner set-up', 'We agree the cohort, schedule and goals with your school, institute or company.'],
      ['Weekly practice', 'Facilitated sessions, AI tools and guided projects that fit your calendar.'],
      ['Portfolio reviews', 'Regular feedback so the work is ready to show.'],
      ['Showcase', 'Learners present their capstones; you receive progress and outcome reports.'],
    ],
    proofTitle: 'Behind the programme',
    pricingTitle: 'Programmes and pricing',
    pricingBody: 'Choose the format that fits your institution. Every plan can start with a consultation.',
    checkout: 'Pay securely', checkoutNote: 'Secure payment by Stripe.',
    faqs: [
      ['Who is Future Ready for?', 'Final-year students, graduates, vocational learners and company teams who need practical AI and digital skills.'],
      ['Do learners need a technical background?', 'No. The curriculum starts from the basics and builds to real projects.'],
      ['What do participants leave with?', 'A portfolio with an app, an AI workflow, an automation and a capstone, plus a certificate of completion.'],
      ['Who designed the programme?', 'Our founder designed and taught web-development programmes with NGOs in Kenya from 2018 to 2022, training 30+ developers in cohorts of 15–30.'],
    ],
    ctaTitle: 'Give your learners evidence, not just certificates.', ctaSub: 'Book a call to plan a cohort, or take the fit check.',
  },
  fr: {
    k: 'Talents', name: 'Future Ready',
    gap: 'Ferme : diplômes sans preuves, équipes qui craignent les outils IA.',
    body: 'Des compétences IA concrètes pour équipes et diplômés. Chacun repart avec un portfolio : une application, un workflow IA, une automatisation et un projet final.',
    points: ['Pratique, pas des slides', 'Le portfolio avant le certificat', 'Pour écoles, instituts et entreprises'],
    heroSub: 'Un programme de préparation professionnelle, pas un cours d’informatique. Les apprenants construisent de vraies choses avec des outils IA et repartent avec un portfolio qui prouve ce qu’ils savent faire.',
    problemTitle: 'Les diplômés sortent avec des certificats. Les employeurs demandent des preuves.',
    problemBody: 'On dit aux jeunes d’« apprendre le numérique », mais ils livrent rarement quelque chose de concret. Future Ready est construit autour de projets : chaque participant peut montrer à un employeur, un client ou un bailleur ce qu’il a réalisé.',
    buildTitle: 'Ce que les participants construisent',
    build: [
      ['Une application', 'Une application web fonctionnelle, conçue et mise en ligne par l’apprenant.'],
      ['Un workflow IA', 'Une vraie tâche réalisée plus vite et mieux avec l’IA, documentée étape par étape.'],
      ['Une automatisation', 'Un processus répétitif transformé en quelque chose qui tourne seul.'],
      ['Un projet final', 'Un projet pour une vraie organisation ou idée, présenté devant un jury.'],
      ['Un portfolio', 'Une page qui réunit les preuves pour employeurs et clients.'],
      ['Compétences de carrière', 'Communication, bases du freelancing et comment créer du travail, pas seulement en trouver.'],
    ],
    stepsTitle: 'Déroulement du programme',
    steps: [
      ['Mise en place', 'Nous fixons la cohorte, le calendrier et les objectifs avec votre école, institut ou entreprise.'],
      ['Pratique hebdomadaire', 'Séances animées, outils IA et projets guidés adaptés à votre calendrier.'],
      ['Revues de portfolio', 'Des retours réguliers pour que le travail soit présentable.'],
      ['Présentation finale', 'Les apprenants présentent leurs projets ; vous recevez des rapports de progression et de résultats.'],
    ],
    proofTitle: 'Derrière le programme',
    pricingTitle: 'Formules et tarifs',
    pricingBody: 'Choisissez la formule adaptée à votre établissement. Chaque formule peut commencer par une consultation.',
    checkout: 'Payer en ligne', checkoutNote: 'Paiement sécurisé par Stripe.',
    faqs: [
      ['À qui s’adresse Future Ready ?', 'Aux élèves de terminale, diplômés, apprenants en formation professionnelle et équipes d’entreprise qui ont besoin de compétences IA et numériques concrètes.'],
      ['Faut-il un profil technique ?', 'Non. Le programme part des bases et mène à de vrais projets.'],
      ['Avec quoi repartent les participants ?', 'Un portfolio avec une application, un workflow IA, une automatisation et un projet final, ainsi qu’une attestation.'],
      ['Qui a conçu le programme ?', 'Notre fondateur a conçu et enseigné des programmes de développement web avec des ONG au Kenya de 2018 à 2022, formant plus de 30 développeurs par cohortes de 15 à 30.'],
    ],
    ctaTitle: 'Donnez à vos apprenants des preuves, pas seulement des certificats.', ctaSub: 'Réservez un appel pour planifier une cohorte, ou faites le diagnostic.',
  },
  es: {
    k: 'Talento', name: 'Future Ready',
    gap: 'Cierra: títulos sin evidencias, equipos con miedo a la IA.',
    body: 'Capacidad práctica en IA para equipos y egresados. Todos salen con un portafolio: una app, un flujo con IA, una automatización y un proyecto final.',
    points: ['Práctico, no diapositivas', 'Portafolio antes que certificado', 'Para colegios, institutos y empresas'],
    heroSub: 'Un programa de preparación profesional, no un curso de informática. Los participantes construyen cosas reales con herramientas de IA y salen con un portafolio que demuestra lo que saben hacer.',
    problemTitle: 'Los egresados terminan con certificados. Los empleadores piden evidencias.',
    problemBody: 'A los jóvenes se les dice que «aprendan habilidades digitales», pero rara vez entregan algo real. Future Ready gira en torno a proyectos, para que cada participante pueda mostrar a un empleador, cliente o financiador lo que construyó.',
    buildTitle: 'Qué construyen los participantes',
    build: [
      ['Una app', 'Una app web funcional, diseñada y publicada por el participante.'],
      ['Un flujo con IA', 'Una tarea real hecha más rápido y mejor con IA, documentada paso a paso.'],
      ['Una automatización', 'Un proceso repetitivo convertido en algo que funciona solo.'],
      ['Un proyecto final', 'Un proyecto para una organización o idea real, presentado ante un jurado.'],
      ['Un portafolio', 'Una página que reúne las evidencias para empleadores y clientes.'],
      ['Habilidades profesionales', 'Comunicación, bases del trabajo freelance y cómo crear trabajo, no solo encontrarlo.'],
    ],
    stepsTitle: 'Cómo funciona el programa',
    steps: [
      ['Puesta en marcha', 'Acordamos la cohorte, el calendario y los objetivos con tu colegio, instituto o empresa.'],
      ['Práctica semanal', 'Sesiones guiadas, herramientas de IA y proyectos que encajan en tu calendario.'],
      ['Revisiones de portafolio', 'Comentarios regulares para que el trabajo esté listo para mostrar.'],
      ['Presentación final', 'Los participantes presentan sus proyectos; recibes informes de progreso y resultados.'],
    ],
    proofTitle: 'Detrás del programa',
    pricingTitle: 'Programas y precios',
    pricingBody: 'Elige el formato que mejor se adapte a tu institución. Todos los planes pueden empezar con una consulta.',
    checkout: 'Pagar de forma segura', checkoutNote: 'Pago seguro con Stripe.',
    faqs: [
      ['¿Para quién es Future Ready?', 'Para estudiantes de último año, egresados, alumnos de formación profesional y equipos de empresa que necesitan habilidades prácticas de IA y digitales.'],
      ['¿Hace falta experiencia técnica?', 'No. El programa empieza por lo básico y llega a proyectos reales.'],
      ['¿Con qué salen los participantes?', 'Con un portafolio que incluye una app, un flujo con IA, una automatización y un proyecto final, además de un certificado.'],
      ['¿Quién diseñó el programa?', 'Nuestro fundador diseñó e impartió programas de desarrollo web con ONG en Kenia de 2018 a 2022 y formó a más de 30 desarrolladores en grupos de 15 a 30.'],
    ],
    ctaTitle: 'Da a tus participantes evidencias, no solo certificados.', ctaSub: 'Reserva una llamada para planificar una cohorte o haz el diagnóstico.',
  },
  de: {
    k: 'Talente', name: 'Future Ready',
    gap: 'Schließt: Zertifikate ohne Nachweis, Teams mit Angst vor KI-Tools.',
    body: 'Praktische KI-Kompetenz für Teams und Absolventen. Alle gehen mit einem Portfolio: eine App, ein KI-Workflow, eine Automatisierung und ein Abschlussprojekt.',
    points: ['Praxis statt Folien', 'Portfolio statt nur Zertifikat', 'Für Schulen, Institute und Unternehmen'],
    heroSub: 'Ein Programm für Berufsreife, kein Computerkurs. Die Teilnehmenden bauen mit KI-Tools echte Dinge und gehen mit einem Portfolio, das zeigt, was sie können.',
    problemTitle: 'Absolventen haben Zertifikate. Arbeitgeber wollen Nachweise.',
    problemBody: 'Jungen Menschen wird gesagt, sie sollen „digitale Skills lernen“, doch selten entsteht etwas Echtes. Future Ready ist projektbasiert, damit alle Teilnehmenden Arbeitgebern, Kunden oder Geldgebern zeigen können, was sie gebaut haben.',
    buildTitle: 'Was die Teilnehmenden bauen',
    build: [
      ['Eine App', 'Eine funktionierende Web-App, selbst entworfen und veröffentlicht.'],
      ['Einen KI-Workflow', 'Eine echte Aufgabe, mit KI schneller und besser erledigt und Schritt für Schritt dokumentiert.'],
      ['Eine Automatisierung', 'Ein wiederkehrender Prozess, der künftig von selbst läuft.'],
      ['Ein Abschlussprojekt', 'Ein Projekt für eine echte Organisation oder Idee, vor einer Jury präsentiert.'],
      ['Ein Portfolio', 'Eine Seite, die alle Nachweise für Arbeitgeber und Kunden bündelt.'],
      ['Berufliche Fähigkeiten', 'Kommunikation, Freelancing-Grundlagen und wie man Arbeit schafft, nicht nur findet.'],
    ],
    stepsTitle: 'So läuft das Programm',
    steps: [
      ['Partner-Setup', 'Wir legen Gruppe, Zeitplan und Ziele mit Ihrer Schule, Ihrem Institut oder Unternehmen fest.'],
      ['Wöchentliche Praxis', 'Begleitete Sessions, KI-Tools und angeleitete Projekte passend zu Ihrem Kalender.'],
      ['Portfolio-Reviews', 'Regelmäßiges Feedback, damit die Arbeit vorzeigbar ist.'],
      ['Präsentation', 'Die Teilnehmenden präsentieren ihre Projekte; Sie erhalten Fortschritts- und Ergebnisberichte.'],
    ],
    proofTitle: 'Hinter dem Programm',
    pricingTitle: 'Programme und Preise',
    pricingBody: 'Wählen Sie das Format, das zu Ihrer Einrichtung passt. Jedes Angebot kann mit einer Beratung beginnen.',
    checkout: 'Sicher bezahlen', checkoutNote: 'Sichere Zahlung über Stripe.',
    faqs: [
      ['Für wen ist Future Ready?', 'Für Abschlussjahrgänge, Absolventen, Auszubildende und Unternehmensteams, die praktische KI- und Digitalkompetenz brauchen.'],
      ['Braucht man technische Vorkenntnisse?', 'Nein. Der Lehrplan beginnt bei den Grundlagen und führt zu echten Projekten.'],
      ['Womit gehen die Teilnehmenden?', 'Mit einem Portfolio aus App, KI-Workflow, Automatisierung und Abschlussprojekt sowie einer Teilnahmebescheinigung.'],
      ['Wer hat das Programm entwickelt?', 'Unser Gründer hat von 2018 bis 2022 mit NGOs in Kenia Webentwicklungsprogramme konzipiert und unterrichtet und über 30 Entwickler in Gruppen von 15 bis 30 ausgebildet.'],
    ],
    ctaTitle: 'Geben Sie Ihren Lernenden Nachweise, nicht nur Zertifikate.', ctaSub: 'Buchen Sie ein Gespräch zur Planung einer Gruppe oder machen Sie den Eignungscheck.',
  },
  ar: {
    k: 'المواهب', name: 'جاهز للمستقبل',
    gap: 'تغلق: شهادات بلا دليل، وفرق تخشى أدوات الذكاء الاصطناعي.',
    body: 'قدرات عملية في الذكاء الاصطناعي للفرق والخريجين. يخرج كل مشارك بملف أعمال: تطبيق ومسار عمل ذكي وأتمتة ومشروع ختامي.',
    points: ['تطبيق عملي لا شرائح عرض', 'ملف الأعمال قبل الشهادة', 'للمدارس والمعاهد والشركات'],
    heroSub: 'برنامج للجاهزية المهنية وليس دورة حاسوب. يبني المشاركون أشياء حقيقية بأدوات الذكاء الاصطناعي ويخرجون بملف أعمال يثبت ما يستطيعون فعله.',
    problemTitle: 'يتخرج الطلاب بشهادات، ويطلب أصحاب العمل أدلة.',
    problemBody: 'يُقال للشباب «تعلّموا المهارات الرقمية» لكنهم نادراً ما يُنجزون شيئاً حقيقياً. بُني برنامج جاهز للمستقبل حول المشاريع، ليستطيع كل مشارك أن يُري صاحب العمل أو العميل أو الممول ما بناه.',
    buildTitle: 'ما يبنيه المشاركون',
    build: [
      ['تطبيق', 'تطبيق ويب يعمل، يصممه المتعلم وينشره بنفسه.'],
      ['مسار عمل ذكي', 'مهمة حقيقية تُنجز أسرع وأفضل بالذكاء الاصطناعي، موثقة خطوة بخطوة.'],
      ['أتمتة', 'عملية متكررة تتحول إلى شيء يعمل وحده.'],
      ['مشروع ختامي', 'مشروع لمؤسسة أو فكرة حقيقية يُعرض أمام لجنة.'],
      ['ملف أعمال', 'صفحة واحدة تجمع الأدلة لأصحاب العمل والعملاء.'],
      ['مهارات مهنية', 'التواصل وأساسيات العمل الحر وكيف تصنع عملاً لا أن تبحث عنه فقط.'],
    ],
    stepsTitle: 'كيف يسير البرنامج',
    steps: [
      ['إعداد الشراكة', 'نتفق على الدفعة والجدول والأهداف مع مدرستك أو معهدك أو شركتك.'],
      ['تدريب أسبوعي', 'جلسات موجهة وأدوات ذكاء اصطناعي ومشاريع تناسب جدولك.'],
      ['مراجعة ملفات الأعمال', 'ملاحظات منتظمة ليصبح العمل جاهزاً للعرض.'],
      ['العرض الختامي', 'يعرض المشاركون مشاريعهم وتتلقى تقارير التقدم والنتائج.'],
    ],
    proofTitle: 'خلف البرنامج',
    pricingTitle: 'البرامج والأسعار',
    pricingBody: 'اختر الصيغة المناسبة لمؤسستك. يمكن أن تبدأ كل خطة باستشارة.',
    checkout: 'ادفع بأمان', checkoutNote: 'دفع آمن عبر Stripe.',
    faqs: [
      ['لمن برنامج جاهز للمستقبل؟', 'لطلاب السنة النهائية والخريجين ومتعلمي التدريب المهني وفرق الشركات الذين يحتاجون إلى مهارات عملية في الذكاء الاصطناعي والرقمنة.'],
      ['هل يحتاج المتعلمون إلى خلفية تقنية؟', 'لا. يبدأ المنهج من الأساسيات ويصل إلى مشاريع حقيقية.'],
      ['بماذا يخرج المشاركون؟', 'بملف أعمال يضم تطبيقاً ومسار عمل ذكياً وأتمتة ومشروعاً ختامياً، إضافة إلى شهادة إتمام.'],
      ['من صمم البرنامج؟', 'صمم مؤسسنا ودرّس برامج تطوير الويب مع منظمات في كينيا بين 2018 و2022، ودرّب أكثر من 30 مطوراً في دفعات من 15 إلى 30.'],
    ],
    ctaTitle: 'امنح متعلميك أدلة لا شهادات فقط.', ctaSub: 'احجز مكالمة لتخطيط دفعة أو أجرِ فحص الملاءمة.',
  },
}

export const services: Service[] = [
  { slug: 'agentic-systems', assessment: 'agentic-softwares', checkoutPlan: 'agentic_deposit', img: 'team-table', heroImg: 'tower-bw', related: ['shuleos', 'kabinda-lodge', 'epic-drc', 'digni-results', 'cadran'], copy: agentic },
  { slug: 'ai-employee', assessment: 'ai-employee', checkoutPlan: 'ai_employee', img: 'phone-desk', heroImg: 'boulevard', related: ['fremo-medical', 'shep-engineering', 'glamsquad-kenya'], copy: aiEmployee },
  { slug: 'future-ready', assessment: 'future-ready', img: 'students-steps', heroImg: 'classroom-laptop', related: [], copy: futureReady },
]

export const getService = (slug: string) => services.find((s) => s.slug === slug)
export const servicePath = (slug: ServiceSlug) => `/services/${slug}`

/** Labels for the Future Ready programme cards and shared service-page UI. */
export const svcUi: Record<Lang, {
  fitCheck: string; book: string; popular: string; schools: string; institutes: string; everyone: string
  paySemester: string; payYear: string; payCenter: string; payGuided: string; consultFirst: string; redirecting: string
  founderNote: string; builtFor: string; seeService: string
}> = {
  en: { fitCheck: 'Take the fit check', book: 'Book a call', popular: 'Most chosen', schools: 'For schools', institutes: 'For institutes', everyone: 'For individuals', paySemester: 'Pay per semester', payYear: 'Pay per year', payCenter: 'Pay per centre', payGuided: 'Enrol now', consultFirst: 'Book a consultation first', redirecting: 'Redirecting to secure checkout…', founderNote: 'Designed by a founder who has taught developers since 2018.', builtFor: 'What it closes', seeService: 'See the service' },
  fr: { fitCheck: 'Faire le diagnostic', book: 'Réserver un appel', popular: 'Le plus choisi', schools: 'Pour les écoles', institutes: 'Pour les instituts', everyone: 'Pour les particuliers', paySemester: 'Payer au semestre', payYear: 'Payer à l’année', payCenter: 'Payer par centre', payGuided: 'S’inscrire', consultFirst: 'Réserver d’abord une consultation', redirecting: 'Redirection vers le paiement sécurisé…', founderNote: 'Conçu par un fondateur qui forme des développeurs depuis 2018.', builtFor: 'Ce que cela ferme', seeService: 'Voir le service' },
  es: { fitCheck: 'Hacer el diagnóstico', book: 'Reservar llamada', popular: 'El más elegido', schools: 'Para colegios', institutes: 'Para institutos', everyone: 'Para personas', paySemester: 'Pagar por semestre', payYear: 'Pagar por año', payCenter: 'Pagar por centro', payGuided: 'Inscribirme', consultFirst: 'Reservar antes una consulta', redirecting: 'Redirigiendo al pago seguro…', founderNote: 'Diseñado por un fundador que forma desarrolladores desde 2018.', builtFor: 'Qué cierra', seeService: 'Ver el servicio' },
  de: { fitCheck: 'Eignungscheck starten', book: 'Gespräch buchen', popular: 'Am häufigsten gewählt', schools: 'Für Schulen', institutes: 'Für Institute', everyone: 'Für Einzelpersonen', paySemester: 'Pro Semester zahlen', payYear: 'Jährlich zahlen', payCenter: 'Pro Zentrum zahlen', payGuided: 'Jetzt einschreiben', consultFirst: 'Zuerst eine Beratung buchen', redirecting: 'Weiterleitung zur sicheren Zahlung…', founderNote: 'Entwickelt von einem Gründer, der seit 2018 Entwickler ausbildet.', builtFor: 'Was es schließt', seeService: 'Zur Leistung' },
  ar: { fitCheck: 'ابدأ فحص الملاءمة', book: 'احجز مكالمة', popular: 'الأكثر اختياراً', schools: 'للمدارس', institutes: 'للمعاهد', everyone: 'للأفراد', paySemester: 'الدفع لكل فصل', payYear: 'الدفع سنوياً', payCenter: 'الدفع لكل مركز', payGuided: 'سجّل الآن', consultFirst: 'احجز استشارة أولاً', redirecting: 'جارٍ التحويل إلى الدفع الآمن…', founderNote: 'صممه مؤسس يدرّب المطورين منذ 2018.', builtFor: 'ما الذي تغلقه', seeService: 'عرض الخدمة' },
}
